//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Server.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleSendResumen
    {
        public int idDetalleSendResumen { get; set; }
        public Nullable<int> idSendResumen { get; set; }
        public string tipoDocumento { get; set; }
        public string serie { get; set; }
        public Nullable<int> inicio { get; set; }
        public Nullable<int> fin { get; set; }
        public Nullable<decimal> gravada { get; set; }
        public Nullable<decimal> exoneradas { get; set; }
        public Nullable<decimal> inafectas { get; set; }
        public Nullable<decimal> igv { get; set; }
    }
}
