//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Server.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificacionSunat
    {
        public int idVerificacionSunat { get; set; }
        public string idTicket { get; set; }
        public string empresa { get; set; }
        public string numerodocumento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string resultado { get; set; }
        public Nullable<bool> isActivo { get; set; }
        public string tipo_envio { get; set; }
        public Nullable<int> codigopaciente { get; set; }
        public string pathfile { get; set; }
        public string tipodocumento { get; set; }
        public string usuario { get; set; }
        public Nullable<int> sucursal { get; set; }
    }
}
