//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADJUNTO_CARTAGARANTIA
    {
        public int id { get; set; }
        public string idCarta { get; set; }
        public int idPaciente { get; set; }
        public int idAdjunto { get; set; }
    }
}
