//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_Almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AL_Almacen()
        {
            this.AL_Stock_Diario = new HashSet<AL_Stock_Diario>();
            this.AL_Stock_Current = new HashSet<AL_Stock_Current>();
            this.AL_Stock_Item = new HashSet<AL_Stock_Item>();
        }
    
        public int AL_AlmacenId { get; set; }
        public string Nombre { get; set; }
        public System.DateTime AuFecReg { get; set; }
        public string AuUsuReg { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CodigoEquivalente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AL_Stock_Diario> AL_Stock_Diario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AL_Stock_Current> AL_Stock_Current { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AL_Stock_Item> AL_Stock_Item { get; set; }
    }
}
