//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATENCION()
        {
            this.EXAMENXATENCION = new HashSet<EXAMENXATENCION>();
            this.LIBROCAJA = new HashSet<LIBROCAJA>();
        }
    
        public System.DateTime fechayhora { get; set; }
        public int numeroatencion { get; set; }
        public int codigopaciente { get; set; }
        public string cmp { get; set; }
        public int codigocompaniaseguro { get; set; }
        public string ruc { get; set; }
        public int numerocita { get; set; }
        public int codigomodalidad { get; set; }
        public int codigounidad { get; set; }
        public int peso { get; set; }
        public float talla { get; set; }
        public int edad { get; set; }
        public string codigousuario { get; set; }
        public string numerocarnetseguro { get; set; }
        public Nullable<int> codigocompaniaseguroChanged { get; set; }
        public string SitedOrden { get; set; }
        public string SitedCobertura { get; set; }
        public string CodigoSegOnline { get; set; }
        public Nullable<bool> isChangePeso { get; set; }
        public Nullable<int> newPeso { get; set; }
        public Nullable<bool> isChangeTalla { get; set; }
        public Nullable<double> newTalla { get; set; }
        public Nullable<bool> isChangeEdad { get; set; }
        public Nullable<System.DateTime> newEdad { get; set; }
        public string observacionAten { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsReimprimible { get; set; }
        public bool isDelivery { get; set; }
        public Nullable<int> numeroTicket { get; set; }
        public Nullable<bool> IsPlacaDejada { get; set; }
        public bool isImpresoSegOnline { get; set; }
    
        public virtual CITA CITA { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAMENXATENCION> EXAMENXATENCION { get; set; }
        public virtual MEDICOEXTERNO MEDICOEXTERNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIBROCAJA> LIBROCAJA { get; set; }
    }
}
