//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CG_SolicituCarta_Historial
    {
        public int idDetSol { get; set; }
        public Nullable<int> idSolicitud { get; set; }
        public string usuario { get; set; }
        public string comentarios { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
    
        public virtual CG_SolicitudCarta CG_SolicitudCarta { get; set; }
    }
}
