//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROL_SEDACION
    {
        public string codigoregistro { get; set; }
        public string anestesiologo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> codigopaciente { get; set; }
        public Nullable<int> cantidadestudio { get; set; }
        public Nullable<int> codigocompaniaseguro { get; set; }
        public Nullable<int> codigoclinica { get; set; }
        public string montosedacion { get; set; }
        public Nullable<decimal> tipodecambio { get; set; }
        public string motivo { get; set; }
        public string estado { get; set; }
        public string tiposedacion { get; set; }
        public Nullable<int> examen { get; set; }
        public string usuario { get; set; }
    }
}
