//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleReciboProvisional
    {
        public int idDetRecibo { get; set; }
        public int idRecibo { get; set; }
        public int formapago { get; set; }
        public decimal monto { get; set; }
        public System.DateTime fec_registro { get; set; }
        public string usuario { get; set; }
        public string numeroreferencia { get; set; }
        public int moneda { get; set; }
        public Nullable<decimal> tipocambio { get; set; }
    
        public virtual TARJETA TARJETA { get; set; }
        public virtual ReciboProvisional ReciboProvisional { get; set; }
    }
}
