//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIO_COMPANIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTUDIO_COMPANIA()
        {
            this.DETALLEDOCUMENTO = new HashSet<DETALLEDOCUMENTO>();
        }
    
        public string codigoestudio { get; set; }
        public int codigocompaniaseguro { get; set; }
        public string ruc { get; set; }
        public float precioreal { get; set; }
        public float preciobruto { get; set; }
        public int codigoclase { get; set; }
        public int codigomodalidad { get; set; }
        public int codigounidad { get; set; }
        public int codigomoneda { get; set; }
    
        public virtual ESTUDIO ESTUDIO { get; set; }
        public virtual COMPANIASEGURO COMPANIASEGURO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEDOCUMENTO> DETALLEDOCUMENTO { get; set; }
    }
}
