//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIZCALIZACION
    {
        public int codigofizcaliza { get; set; }
        public System.DateTime hora { get; set; }
        public System.DateTime fecha { get; set; }
        public string nombrepc { get; set; }
        public string descripcioncambio { get; set; }
        public string codigousuario { get; set; }
        public Nullable<int> codigohorario { get; set; }
    }
}
