//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario_Tecnologo
    {
        public int idProgramacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> inicio { get; set; }
        public Nullable<System.TimeSpan> fin { get; set; }
        public Nullable<int> codigoequipo { get; set; }
        public string tecnologo { get; set; }
        public Nullable<System.DateTime> fec_update { get; set; }
        public string user_update { get; set; }
        public Nullable<int> unidad { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
