//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboProvisional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReciboProvisional()
        {
            this.DetalleReciboProvisional = new HashSet<DetalleReciboProvisional>();
        }
    
        public int idRecibo { get; set; }
        public int numerocita { get; set; }
        public int codigopaciente { get; set; }
        public System.DateTime fecha_reg { get; set; }
        public string motivo { get; set; }
        public decimal monto_recibido { get; set; }
        public decimal monto_total { get; set; }
        public string usuario { get; set; }
        public bool isActivo { get; set; }
        public int empresa { get; set; }
        public Nullable<System.DateTime> fecha_cancelacion { get; set; }
        public string usu_cancela { get; set; }
        public string comentarios { get; set; }
        public Nullable<System.DateTime> fecha_aprueba { get; set; }
        public string usu_aprueba { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReciboProvisional> DetalleReciboProvisional { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual USUARIO USUARIO2 { get; set; }
        public virtual USUARIO USUARIO3 { get; set; }
    }
}
