//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIE
    {
        public Nullable<int> fin { get; set; }
        public Nullable<int> inicio { get; set; }
        public int correlativo { get; set; }
        public string serie1 { get; set; }
        public string tipo { get; set; }
        public int idserie { get; set; }
        public Nullable<bool> IsActiveCaja { get; set; }
    }
}
