//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKT_Historial
    {
        public int idhistoria { get; set; }
        public Nullable<int> idcounter { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> counter_origen { get; set; }
        public Nullable<int> idticketera { get; set; }
    
        public virtual TKT_Counter TKT_Counter { get; set; }
        public virtual TKT_Counter TKT_Counter1 { get; set; }
        public virtual TKT_Ticketera TKT_Ticketera { get; set; }
    }
}
