//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.ServiceResocentro {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceResocentro.IWSAsyncCallSeguimiento")]
    public interface IWSAsyncCallSeguimiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSAsyncCallSeguimiento/ActualizarListaEncuesta", ReplyAction="http://tempuri.org/IWSAsyncCallSeguimiento/ActualizarListaEncuestaResponse")]
        bool ActualizarListaEncuesta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSAsyncCallSeguimiento/ActualizarListaEncuesta", ReplyAction="http://tempuri.org/IWSAsyncCallSeguimiento/ActualizarListaEncuestaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarListaEncuestaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSAsyncCallSeguimientoChannel : Resocentro_Desktop.ServiceResocentro.IWSAsyncCallSeguimiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAsyncCallSeguimientoClient : System.ServiceModel.ClientBase<Resocentro_Desktop.ServiceResocentro.IWSAsyncCallSeguimiento>, Resocentro_Desktop.ServiceResocentro.IWSAsyncCallSeguimiento {
        
        public WSAsyncCallSeguimientoClient() {
        }
        
        public WSAsyncCallSeguimientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAsyncCallSeguimientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAsyncCallSeguimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAsyncCallSeguimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ActualizarListaEncuesta() {
            return base.Channel.ActualizarListaEncuesta();
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarListaEncuestaAsync() {
            return base.Channel.ActualizarListaEncuestaAsync();
        }
    }
}
