//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificacionesMedicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int jerarquia { get; set; }
        public string estadousuario { get; set; }
        public string siglas { get; set; }
        public string codigousuario { get; set; }
        public string dni { get; set; }
        public bool bloqueado { get; set; }
        public string contrasena { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> isEnf { get; set; }
        public Nullable<bool> isAnes { get; set; }
        public string username { get; set; }
        public string Acro { get; set; }
        public Nullable<int> CurrentUnidad { get; set; }
        public bool isSessionLocked { get; set; }
        public string User_Uid { get; set; }
        public Nullable<int> AreaId { get; set; }
    }
}
