//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificacionesMedicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuesta_Satisfaccion
    {
        public int idencuesta { get; set; }
        public int numeroatecion { get; set; }
        public Nullable<System.DateTime> fec_inicio { get; set; }
        public Nullable<System.DateTime> fec_fin { get; set; }
        public int paciente { get; set; }
        public Nullable<bool> p1 { get; set; }
        public Nullable<bool> p2 { get; set; }
        public Nullable<bool> p3 { get; set; }
        public string usu_reg { get; set; }
        public Nullable<System.DateTime> fec_ini { get; set; }
        public Nullable<bool> isTerminado { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual PACIENTE PACIENTE1 { get; set; }
    }
}
