//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificacionesMedicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMENXATENCION
    {
        public int codigo { get; set; }
        public int numeroatencion { get; set; }
        public int codigopaciente { get; set; }
        public int numerocita { get; set; }
        public int codigocompaniaseguro { get; set; }
        public string ruc { get; set; }
        public int codigoequipo { get; set; }
        public System.DateTime horaatencion { get; set; }
        public string codigoestudio { get; set; }
        public int codigoclase { get; set; }
        public int codigomodalidad { get; set; }
        public int codigounidad { get; set; }
        public string estadoestudio { get; set; }
        public string prioridad { get; set; }
        public string turnomedico { get; set; }
        public Nullable<int> encu_tipo { get; set; }
        public Nullable<int> codigoequipoFinal { get; set; }
        public Nullable<int> EstadoInforme { get; set; }
        public string motivo { get; set; }
        public string otros_motivos { get; set; }
        public string usu_cancela { get; set; }
        public Nullable<System.DateTime> fecha_cancela { get; set; }
        public Nullable<bool> IsAcopied { get; set; }
        public Nullable<bool> IsAmpliInDemand { get; set; }
        public Nullable<int> AmpliCodigo { get; set; }
        public Nullable<int> CodigoDeEstudioOrigen { get; set; }
        public Nullable<bool> isLocked { get; set; }
        public Nullable<int> EstadoEncuesta { get; set; }
        public Nullable<int> equipoAsignado { get; set; }
        public Nullable<bool> IsPostProInDemand { get; set; }
        public Nullable<int> GrupoMedico { get; set; }
        public Nullable<bool> isImpax { get; set; }
        public Nullable<System.DateTime> Fec_Rev_Impax { get; set; }
        public string usu_Rev_Impax { get; set; }
        public Nullable<bool> IsAudible { get; set; }
        public string UserTemporal { get; set; }
        public Nullable<bool> IsMoreThanOnePage { get; set; }
        public string UrlXero { get; set; }
        public Nullable<bool> IsTranscriInDemand { get; set; }
        public string MedProceAtro { get; set; }
        public Nullable<bool> IsDictado { get; set; }
        public string AmpliMotivo { get; set; }
        public Nullable<System.DateTime> FecAlternativaIniEntrega { get; set; }
        public Nullable<bool> IsPediatrico { get; set; }
        public string turnomedicoOld { get; set; }
        public Nullable<bool> IsSensible { get; set; }
        public Nullable<bool> isSensibleB { get; set; }
        public string consentimiento { get; set; }
        public Nullable<bool> isSensibleA { get; set; }
        public Nullable<bool> IsValidRequired { get; set; }
        public string num_oa_sjt { get; set; }
        public Nullable<bool> IsVerifiedTurno { get; set; }
        public string MedAsigRea { get; set; }
        public Nullable<System.DateTime> FecAlternativaIniEntregaAutor { get; set; }
        public bool isOperado { get; set; }
        public bool isAngio { get; set; }
        public string SensibleGrupo { get; set; }
        public string prioridadMotivo { get; set; }
        public string prioridadUser { get; set; }
        public Nullable<System.DateTime> prioridadFecReg { get; set; }
        public Nullable<System.DateTime> AmpliSoliFec { get; set; }
        public string PauseEstado { get; set; }
        public string PauseMotivo { get; set; }
        public Nullable<System.DateTime> PauseStopFecReg { get; set; }
        public string PauseStopUsuReg { get; set; }
        public Nullable<System.DateTime> PauseReaFecReg { get; set; }
        public string PauseReaUsuReg { get; set; }
        public string num_oa_sjt_doc_tip { get; set; }
        public string num_oa_sjt_doc_ser { get; set; }
        public string num_oa_sjt_doc_num { get; set; }
        public string num_oa_sjt_cod_item { get; set; }
        public string DigitaEst { get; set; }
        public Nullable<System.DateTime> FecAlternativaIniEntregaPag { get; set; }
        public Nullable<System.DateTime> FecAlternativaIniEntregaAutorPag { get; set; }
        public string FecAlternativaIniEntregaPag_M { get; set; }
        public string FecAlternativaIniEntregaAutorPag_M { get; set; }
        public string FecAlternativaIniEntregaAutorPag_U { get; set; }
        public string FecAlternativaIniEntregaPag_U { get; set; }
        public bool isRevisadoCarta { get; set; }
        public bool estadoImagen { get; set; }
        public string ImpactoPrint { get; set; }
        public string ImpactoPrint_user { get; set; }
        public Nullable<System.DateTime> ImpactoPrint_fec { get; set; }
        public Nullable<bool> IsImpreso { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual EQUIPO EQUIPO1 { get; set; }
        public virtual ATENCION ATENCION { get; set; }
        public virtual ESTUDIO ESTUDIO { get; set; }
    }
}
