//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificacionesMedicos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DATABASEGENERALEntities : DbContext
    {
        public DATABASEGENERALEntities()
            : base("name=DATABASEGENERALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Encuesta> Encuesta { get; set; }
        public virtual DbSet<EXAMENXATENCION> EXAMENXATENCION { get; set; }
        public virtual DbSet<Encuesta_Satisfaccion> Encuesta_Satisfaccion { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<EQUIPO> EQUIPO { get; set; }
        public virtual DbSet<PACIENTE> PACIENTE { get; set; }
        public virtual DbSet<ATENCION> ATENCION { get; set; }
        public virtual DbSet<ESTUDIO> ESTUDIO { get; set; }
    }
}
