//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASEGURADORA
    {
        public ASEGURADORA()
        {
            this.COMPANIASEGURO = new HashSet<COMPANIASEGURO>();
        }
    
        public string ruc { get; set; }
        public string razonsocial { get; set; }
        public string razoncomercial { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string web { get; set; }
        public string domiciliofiscal { get; set; }
        public string domiciliocomercial { get; set; }
        public string UbigeoId { get; set; }
    
        public virtual ICollection<COMPANIASEGURO> COMPANIASEGURO { get; set; }
        public virtual UBIGEO UBIGEO { get; set; }
    }
}
