//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITORIA_CARTAS_GARANTIA
    {
        public int codigoregistro { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> codigopaciente { get; set; }
        public string numerodecarta { get; set; }
        public string mensaje { get; set; }
        public string codigousuario { get; set; }
        public string tel_registro { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
