//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITA
    {
        public CITA()
        {
            this.ATENCION = new HashSet<ATENCION>();
            this.EXAMENXCITA = new HashSet<EXAMENXCITA>();
        }
    
        public int numerocita { get; set; }
        public int codigopaciente { get; set; }
        public Nullable<int> codigozona { get; set; }
        public Nullable<int> codigoclinica { get; set; }
        public bool citavip { get; set; }
        public bool sedacion { get; set; }
        public float montototal { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public System.DateTime fechareserva { get; set; }
        public bool claustrofobico { get; set; }
        public string observacion { get; set; }
        public string codigocartagarantia { get; set; }
        public string cmp { get; set; }
        public int codigocompaniaseguro { get; set; }
        public string ruc { get; set; }
        public int codigomodalidad { get; set; }
        public int codigounidad { get; set; }
        public bool ampliatorio { get; set; }
        public string nombrepc { get; set; }
        public string codigousuario { get; set; }
        public string categoria { get; set; }
        public string pagdef { get; set; }
        public Nullable<bool> isConfirmado { get; set; }
        public Nullable<bool> isRepro { get; set; }
    
        public virtual ICollection<ATENCION> ATENCION { get; set; }
        public virtual MODALIDAD MODALIDAD { get; set; }
        public virtual COMPANIASEGURO COMPANIASEGURO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual CLINICAHOSPITAL CLINICAHOSPITAL { get; set; }
        public virtual CARTAGARANTIA CARTAGARANTIA { get; set; }
        public virtual ICollection<EXAMENXCITA> EXAMENXCITA { get; set; }
    }
}
