//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASE
    {
        public CLASE()
        {
            this.ESTUDIO = new HashSet<ESTUDIO>();
        }
    
        public string nombreclase { get; set; }
        public int codigoclase { get; set; }
    
        public virtual ICollection<ESTUDIO> ESTUDIO { get; set; }
    }
}
