//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaborador
    {
        public Colaborador()
        {
            this.Planificacion_CompaniaSeguro = new HashSet<Planificacion_CompaniaSeguro>();
            this.CompaniaSeguro_Colaborador = new HashSet<CompaniaSeguro_Colaborador>();
        }
    
        public int idColaborador { get; set; }
        public string apellidos { get; set; }
        public string nombres { get; set; }
        public string dni { get; set; }
        public string cmp { get; set; }
        public string rne { get; set; }
        public string cargo { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<Planificacion_CompaniaSeguro> Planificacion_CompaniaSeguro { get; set; }
        public virtual ICollection<CompaniaSeguro_Colaborador> CompaniaSeguro_Colaborador { get; set; }
    }
}
