//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANIASEGURO
    {
        public COMPANIASEGURO()
        {
            this.ESTUDIO_COMPANIA = new HashSet<ESTUDIO_COMPANIA>();
            this.CITA = new HashSet<CITA>();
            this.CARTAGARANTIA = new HashSet<CARTAGARANTIA>();
            this.Planificacion_CompaniaSeguro = new HashSet<Planificacion_CompaniaSeguro>();
            this.CompaniaSeguro_Colaborador = new HashSet<CompaniaSeguro_Colaborador>();
            this.CompaniaSeguro_Promotor = new HashSet<CompaniaSeguro_Promotor>();
        }
    
        public int codigocompaniaseguro { get; set; }
        public string ruc { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> IsAgrupable { get; set; }
        public Nullable<bool> IsRequested { get; set; }
        public Nullable<bool> IsSCTR { get; set; }
        public Nullable<bool> IsAp { get; set; }
        public Nullable<bool> IsObsolet { get; set; }
        public Nullable<int> GrupoId { get; set; }
        public string correo_facturacion { get; set; }
    
        public virtual ICollection<ESTUDIO_COMPANIA> ESTUDIO_COMPANIA { get; set; }
        public virtual ICollection<CITA> CITA { get; set; }
        public virtual ICollection<CARTAGARANTIA> CARTAGARANTIA { get; set; }
        public virtual ICollection<Planificacion_CompaniaSeguro> Planificacion_CompaniaSeguro { get; set; }
        public virtual ICollection<CompaniaSeguro_Colaborador> CompaniaSeguro_Colaborador { get; set; }
        public virtual ICollection<CompaniaSeguro_Promotor> CompaniaSeguro_Promotor { get; set; }
        public virtual ASEGURADORA ASEGURADORA { get; set; }
    }
}
