//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompaniaSeguro_Colaborador
    {
        public int id { get; set; }
        public int codigocompania { get; set; }
        public int idColaborador { get; set; }
        public bool isactivo { get; set; }
        public string ruc { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual COMPANIASEGURO COMPANIASEGURO { get; set; }
    }
}
