//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public Consulta()
        {
            this.Historia = new HashSet<Historia>();
        }
    
        public int ConsultaId { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Tipo_Estudio { get; set; }
        public string Estudio { get; set; }
        public string Mensaje { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public bool isAtendido { get; set; }
        public Nullable<System.DateTime> Fec_Atencion { get; set; }
        public bool IsEliminado { get; set; }
        public bool isLeido { get; set; }
    
        public virtual ICollection<Historia> Historia { get; set; }
    }
}
