//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversacionIncidente
    {
        public int idConversacion { get; set; }
        public int idIncidente { get; set; }
        public string usuario { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_reg { get; set; }
        public string mensaje { get; set; }
        public bool isDelete { get; set; }
    
        public virtual IncidenteEquipo IncidenteEquipo { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
