//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrelativoMotivo
    {
        public int idCorrelativo { get; set; }
        public int idmotivo { get; set; }
        public int correlativo { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
        public string userRegister { get; set; }
        public string lastGenerado { get; set; }
    
        public virtual MotivoCodigo MotivoCodigo { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
