//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleReporteComisionesMedico
    {
        public int idDetReporte { get; set; }
        public Nullable<int> idReporte { get; set; }
        public Nullable<System.DateTime> fechayhora { get; set; }
        public Nullable<int> cita { get; set; }
        public Nullable<int> atencion { get; set; }
        public Nullable<int> idpaciente { get; set; }
        public string paciente { get; set; }
        public string idestudio { get; set; }
        public string estudio { get; set; }
        public string idmedico { get; set; }
        public string medico { get; set; }
        public Nullable<int> idcia { get; set; }
        public string cia { get; set; }
        public string idpromotor { get; set; }
        public string promotor { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<bool> isAceptado { get; set; }
        public Nullable<bool> isPagado { get; set; }
        public Nullable<bool> isImpreso { get; set; }
        public Nullable<System.DateTime> fec_print { get; set; }
        public string usu_print { get; set; }
        public Nullable<bool> isProcesado { get; set; }
        public Nullable<decimal> comision { get; set; }
        public string modalidad { get; set; }
        public string documento { get; set; }
        public string usu_acep { get; set; }
        public string usu_paga { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
        public string iddocumento { get; set; }
        public string tipo_paciente { get; set; }
        public Nullable<int> codigo { get; set; }
        public string ndocumento { get; set; }
        public Nullable<int> idprocedencia { get; set; }
        public string procedencia { get; set; }
        public Nullable<int> idequipo { get; set; }
        public string equipo { get; set; }
        public string sede { get; set; }
        public Nullable<decimal> por_comision { get; set; }
        public Nullable<int> isespecialidad { get; set; }
        public string especialidad { get; set; }
    
        public virtual ReporteComisionesMedico ReporteComisionesMedico { get; set; }
    }
}
