//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaServicio
    {
        public EmpresaServicio()
        {
            this.EQUIPO = new HashSet<EQUIPO>();
            this.TelefonoEmpresa = new HashSet<TelefonoEmpresa>();
        }
    
        public int idEmpresa { get; set; }
        public string razonsocial { get; set; }
        public string ruc { get; set; }
        public string correoSoporte { get; set; }
        public string correoMantenimiento { get; set; }
        public string codigousuario { get; set; }
    
        public virtual ICollection<EQUIPO> EQUIPO { get; set; }
        public virtual ICollection<TelefonoEmpresa> TelefonoEmpresa { get; set; }
    }
}
