//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO
    {
        public EQUIPO()
        {
            this.EQUIPO_ESTUDIO = new HashSet<EQUIPO_ESTUDIO>();
            this.EXAMENXATENCION = new HashSet<EXAMENXATENCION>();
            this.HORARIO = new HashSet<HORARIO>();
            this.EXAMENXATENCION1 = new HashSet<EXAMENXATENCION>();
            this.EXAMENXCITA = new HashSet<EXAMENXCITA>();
            this.IncidenteEquipo = new HashSet<IncidenteEquipo>();
        }
    
        public System.DateTime fechaadquirio { get; set; }
        public float intensidad { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public string nombreequipo { get; set; }
        public int codigoequipo { get; set; }
        public int codigosucursal2 { get; set; }
        public int codigounidad2 { get; set; }
        public string estado { get; set; }
        public string ShortDesc { get; set; }
        public string LongDesc { get; set; }
        public Nullable<bool> isIntegrator { get; set; }
        public string PathTemplate { get; set; }
        public bool isSupervisable { get; set; }
        public Nullable<int> codigomodalidad2 { get; set; }
        public string EstadoActual { get; set; }
        public string AETitleConsulta { get; set; }
        public string StationName { get; set; }
        public int anofabricacion { get; set; }
        public int idfrecuencia { get; set; }
        public int idEmpresa { get; set; }
        public System.DateTime fec_emision_Licencia { get; set; }
        public System.DateTime fec_vencimiento_Licencia { get; set; }
        public string licencia { get; set; }
        public bool isEliminado { get; set; }
        public string serienumber { get; set; }
    
        public virtual ICollection<EQUIPO_ESTUDIO> EQUIPO_ESTUDIO { get; set; }
        public virtual ICollection<EXAMENXATENCION> EXAMENXATENCION { get; set; }
        public virtual ICollection<HORARIO> HORARIO { get; set; }
        public virtual ICollection<EXAMENXATENCION> EXAMENXATENCION1 { get; set; }
        public virtual EmpresaServicio EmpresaServicio { get; set; }
        public virtual ICollection<EXAMENXCITA> EXAMENXCITA { get; set; }
        public virtual ICollection<IncidenteEquipo> IncidenteEquipo { get; set; }
        public virtual FrecuenciaMantenimiento FrecuenciaMantenimiento { get; set; }
    }
}
