//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIO_CARTAGAR
    {
        public string codigoestudio { get; set; }
        public string codigocartagarantia { get; set; }
        public string cmp { get; set; }
        public int codigocompaniaseguro { get; set; }
        public string ruc { get; set; }
        public int codigopaciente { get; set; }
        public int codigoclase { get; set; }
        public Nullable<float> cobertura_det { get; set; }
        public Nullable<float> descuento { get; set; }
        public Nullable<int> moneda { get; set; }
        public Nullable<float> preciobruto { get; set; }
    }
}
