//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIO
    {
        public ESTUDIO()
        {
            this.EXAMENXATENCION = new HashSet<EXAMENXATENCION>();
            this.EQUIPO_ESTUDIO = new HashSet<EQUIPO_ESTUDIO>();
            this.ESTUDIO_COMPANIA = new HashSet<ESTUDIO_COMPANIA>();
            this.EXAMENXCITA = new HashSet<EXAMENXCITA>();
        }
    
        public string nombreestudio { get; set; }
        public string codigoestudio { get; set; }
        public int codigoclase { get; set; }
        public string indicacion { get; set; }
        public Nullable<bool> IsValidacion { get; set; }
    
        public virtual ICollection<EXAMENXATENCION> EXAMENXATENCION { get; set; }
        public virtual CLASE CLASE { get; set; }
        public virtual ICollection<EQUIPO_ESTUDIO> EQUIPO_ESTUDIO { get; set; }
        public virtual ICollection<ESTUDIO_COMPANIA> ESTUDIO_COMPANIA { get; set; }
        public virtual ICollection<EXAMENXCITA> EXAMENXCITA { get; set; }
    }
}
