//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialCorrelativo
    {
        public int idHistorial { get; set; }
        public int idmotivo { get; set; }
        public string correlativo { get; set; }
        public string usu_Generador { get; set; }
        public System.DateTime fecha { get; set; }
        public bool Activo { get; set; }
        public string motivo { get; set; }
        public string solicitante { get; set; }
    
        public virtual MotivoCodigo MotivoCodigo { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
