//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidente
    {
        public int idIncidente { get; set; }
        public string idusuario { get; set; }
        public string usuario { get; set; }
        public string problema { get; set; }
        public string importancia { get; set; }
        public string anexo { get; set; }
        public Nullable<System.DateTime> fec_registro { get; set; }
        public Nullable<System.DateTime> fec_lectura { get; set; }
        public string usu_termino { get; set; }
        public string nombre_equipo { get; set; }
        public string ip { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fec_termino { get; set; }
        public string comentarios { get; set; }
        public string aplicativo { get; set; }
        public string usu_lectura { get; set; }
    
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual USUARIO USUARIOLector { get; set; }
        public virtual USUARIO USUARIOTermino { get; set; }
    }
}
