//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institucion_Medico
    {
        public int id { get; set; }
        public int codigoclinica { get; set; }
        public int codigozona { get; set; }
        public string cmp { get; set; }
        public bool isactivo { get; set; }
    
        public virtual MEDICOEXTERNO MEDICOEXTERNO { get; set; }
        public virtual CLINICAHOSPITAL CLINICAHOSPITAL { get; set; }
    }
}
