//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Seguimiento_Produccion
    {
        public int idSeguimiento { get; set; }
        public int examen { get; set; }
        public bool medico { get; set; }
        public bool dni { get; set; }
        public bool clinica { get; set; }
        public bool cobertura { get; set; }
        public bool edad { get; set; }
        public bool talla { get; set; }
        public bool peso { get; set; }
        public bool documento { get; set; }
        public bool adjunto_admision { get; set; }
        public bool adjunto_carta { get; set; }
    }
}
