//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_sistResocentro
    {
        public int idLog { get; set; }
        public Nullable<int> examen { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tabla { get; set; }
        public string campo { get; set; }
        public string oldvalue { get; set; }
        public string newvalue { get; set; }
        public string usuario { get; set; }
        public string modulo { get; set; }
    }
}
