//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICOEXTERNO
    {
        public MEDICOEXTERNO()
        {
            this.ATENCION = new HashSet<ATENCION>();
            this.Institucion_Medico = new HashSet<Institucion_Medico>();
            this.CARTAGARANTIA = new HashSet<CARTAGARANTIA>();
            this.Planificacion = new HashSet<Planificacion>();
            this.AsignacionRepresentanteMedico = new HashSet<AsignacionRepresentanteMedico>();
        }
    
        public string cmp { get; set; }
        public string apellidos { get; set; }
        public string nombres { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fechanacio { get; set; }
        public int codigoespecialidad { get; set; }
        public bool activo { get; set; }
        public string celular { get; set; }
        public string dniMedico { get; set; }
        public Nullable<bool> SexoMedico { get; set; }
        public bool isPaga { get; set; }
        public string categoria { get; set; }
        public string hobby { get; set; }
        public string estado_civil { get; set; }
        public bool isDocumento { get; set; }
        public bool isactivo { get; set; }
        public string cmpCorregido { get; set; }
        public Nullable<System.DateTime> AuFecNew { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsVip { get; set; }
        public string AuUsuNew { get; set; }
        public string re { get; set; }
        public string DocumentoPago { get; set; }
        public Nullable<decimal> saldoAcumulado { get; set; }
        public int tipomedico { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public bool isActiveWeb { get; set; }
        public Nullable<bool> isUserXero { get; set; }
    
        public virtual ICollection<ATENCION> ATENCION { get; set; }
        public virtual ESPECIALIDAD ESPECIALIDAD { get; set; }
        public virtual ICollection<Institucion_Medico> Institucion_Medico { get; set; }
        public virtual TipoMedico TipoMedico1 { get; set; }
        public virtual ICollection<CARTAGARANTIA> CARTAGARANTIA { get; set; }
        public virtual ICollection<Planificacion> Planificacion { get; set; }
        public virtual ICollection<AsignacionRepresentanteMedico> AsignacionRepresentanteMedico { get; set; }
    }
}
