//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planificacion
    {
        public Planificacion()
        {
            this.Planificacion_Documento = new HashSet<Planificacion_Documento>();
        }
    
        public int id { get; set; }
        public int codigoclinica { get; set; }
        public int codigozona { get; set; }
        public string cmp { get; set; }
        public string codigopromotor { get; set; }
        public Nullable<System.DateTime> checkin { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public System.DateTime fecha { get; set; }
        public string motivo { get; set; }
        public bool isRealizada { get; set; }
        public string comentarios { get; set; }
        public bool isCorrecto { get; set; }
    
        public virtual CLINICAHOSPITAL CLINICAHOSPITAL { get; set; }
        public virtual MEDICOEXTERNO MEDICOEXTERNO { get; set; }
        public virtual ICollection<Planificacion_Documento> Planificacion_Documento { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
