//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planificacion_CompaniaSeguro_Documento
    {
        public int id { get; set; }
        public int idplanificacion { get; set; }
        public System.DateTime fecha { get; set; }
        public int tipo { get; set; }
        public string ndocumento { get; set; }
        public string proveedor { get; set; }
        public string categoria { get; set; }
        public string persona_destino { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public decimal total { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public bool isaprobado { get; set; }
        public Nullable<System.DateTime> fecha_isaprobado { get; set; }
        public bool ispagado { get; set; }
        public Nullable<System.DateTime> fecha_ispagado { get; set; }
        public string usu_register { get; set; }
        public string usu_aprueba { get; set; }
        public string usu_paga { get; set; }
        public string usu_update { get; set; }
        public Nullable<System.DateTime> fec_update { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual USUARIO USUARIO2 { get; set; }
        public virtual USUARIO USUARIO3 { get; set; }
        public virtual Planificacion_CompaniaSeguro Planificacion_CompaniaSeguro { get; set; }
    }
}
