//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFORMA
    {
        public int numerodeproforma { get; set; }
        public int codigopaciente { get; set; }
        public string cmp { get; set; }
        public int codigocompaniaseguro { get; set; }
        public string ruc { get; set; }
        public int codigoclinica { get; set; }
        public string tiempoenfermedad { get; set; }
        public System.DateTime fechaemision { get; set; }
        public float montototal { get; set; }
        public string observacion { get; set; }
        public bool sedacion { get; set; }
        public string estado { get; set; }
        public string codigousuario { get; set; }
        public string codigodocescaneado { get; set; }
        public string titular { get; set; }
        public string contratante { get; set; }
        public string poliza { get; set; }
        public Nullable<bool> ishospitalizado { get; set; }
    }
}
