//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteComisionesMedico
    {
        public ReporteComisionesMedico()
        {
            this.DetalleReporteComisionesMedico = new HashSet<DetalleReporteComisionesMedico>();
        }
    
        public int idReporte { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fec_ini { get; set; }
        public Nullable<System.DateTime> fec_fin { get; set; }
    
        public virtual ICollection<DetalleReporteComisionesMedico> DetalleReporteComisionesMedico { get; set; }
    }
}
