//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIE
    {
        public SERIE()
        {
            this.Serie_Equipo = new HashSet<Serie_Equipo>();
        }
    
        public Nullable<int> fin { get; set; }
        public Nullable<int> inicio { get; set; }
        public int correlativo { get; set; }
        public string serie1 { get; set; }
        public string tipo { get; set; }
        public int idserie { get; set; }
        public Nullable<bool> IsActiveCaja { get; set; }
    
        public virtual ICollection<Serie_Equipo> Serie_Equipo { get; set; }
    }
}
