//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie_Equipo
    {
        public int idAsignacion { get; set; }
        public string NombrePc { get; set; }
        public int idSerie { get; set; }
        public int TipoDocumento { get; set; }
        public int Empresa { get; set; }
        public int Sucursal { get; set; }
        public bool isActive { get; set; }
    
        public virtual SERIE SERIE { get; set; }
    }
}
