//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelefonoEmpresa
    {
        public int idTelefono { get; set; }
        public int idEmpresa { get; set; }
        public string numero { get; set; }
        public int idTipoTelefono { get; set; }
    
        public virtual EmpresaServicio EmpresaServicio { get; set; }
        public virtual TipoTelefono TipoTelefono { get; set; }
    }
}
