//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMedico
    {
        public TipoMedico()
        {
            this.MEDICOEXTERNO = new HashSet<MEDICOEXTERNO>();
        }
    
        public int idTipo { get; set; }
        public string descripcion { get; set; }
        public string siglas { get; set; }
    
        public virtual ICollection<MEDICOEXTERNO> MEDICOEXTERNO { get; set; }
    }
}
