//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoIncidente
    {
        public TipoIncidente()
        {
            this.IncidenteEquipo = new HashSet<IncidenteEquipo>();
        }
    
        public int idTipoIndicente { get; set; }
        public string Nombre { get; set; }
        public bool isActivo { get; set; }
    
        public virtual ICollection<IncidenteEquipo> IncidenteEquipo { get; set; }
    }
}
