//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKT_List_Atencion
    {
        public int idList_Atencion { get; set; }
        public int idCounter { get; set; }
        public int idtipo_atencion { get; set; }
    
        public virtual TKT_Tipo_Atencion TKT_Tipo_Atencion { get; set; }
        public virtual TKT_Counter TKT_Counter { get; set; }
    }
}
