//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKT_Tipo_Atencion
    {
        public TKT_Tipo_Atencion()
        {
            this.TKT_List_Atencion = new HashSet<TKT_List_Atencion>();
            this.TKT_Ticketera = new HashSet<TKT_Ticketera>();
        }
    
        public int id_tipo_aten { get; set; }
        public string nombre { get; set; }
        public int idsede { get; set; }
        public bool isEliminado { get; set; }
        public bool isVisible { get; set; }
        public bool isEmergencia { get; set; }
        public int idempresa { get; set; }
        public int orderby { get; set; }
    
        public virtual ICollection<TKT_List_Atencion> TKT_List_Atencion { get; set; }
        public virtual ICollection<TKT_Ticketera> TKT_Ticketera { get; set; }
    }
}
