//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public int id { get; set; }
        public string codigousuario { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
