//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaResocentro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UBIGEO
    {
        public UBIGEO()
        {
            this.PACIENTE = new HashSet<PACIENTE>();
            this.ASEGURADORA = new HashSet<ASEGURADORA>();
        }
    
        public string UbigeoId { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
        public string IneiId { get; set; }
    
        public virtual ICollection<PACIENTE> PACIENTE { get; set; }
        public virtual ICollection<ASEGURADORA> ASEGURADORA { get; set; }
    }
}
