using Resocentro_Desktop.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Telerik.Windows.Controls.Charting;
using Telerik.Windows.Controls.ChartView;

namespace Resocentro_Desktop.Interfaz.InformacionTactica
{
    /// <summary>
    /// Lógica de interacción para frmReporteVentas.xaml
    /// </summary>
    public partial class frmReporteVentas : Window
    {
        MySession session;
        List<Button> listaBotones;
        List<SedeProduccion> detalle;
        List<resumenProduccion> resumen;
        public frmReporteVentas()
        {
            InitializeComponent();
        }
        public void cargarGUI(MySession session)
        {
            this.session = session;

            cboAno.ItemsSource = new UtilDAO().getAño(5);
            cboAno.DisplayMemberPath = "nombre";
            cboAno.SelectedValuePath = "codigo";
            cboAno.SelectedValue = DateTime.Now.Year;
            hiddenRadChart();
            listaBotones = new List<Button>();
            detalle = new List<SedeProduccion>();
            resumen = new List<resumenProduccion>();
        }

        private void hiddenRadChart()
        {
            radChartLine.Visibility = Visibility.Collapsed;
            radChartLine2.Visibility = Visibility.Collapsed;
            radChartLine3.Visibility = Visibility.Collapsed;
            radChartLine4.Visibility = Visibility.Collapsed;
            radChartLine5.Visibility = Visibility.Collapsed;
            radChartLine6.Visibility = Visibility.Collapsed;
            radChartLine7.Visibility = Visibility.Collapsed;
            radChartLine8.Visibility = Visibility.Collapsed;
            radChartLine9.Visibility = Visibility.Collapsed;

            radChartLine.DefaultView.ChartArea.DataSeries.Clear();
            radChartLine2.DefaultView.ChartArea.DataSeries.Clear();
            radChartLine3.DefaultView.ChartArea.DataSeries.Clear();
            radChartLine4.DefaultView.ChartArea.DataSeries.Clear();
            radChartLine5.DefaultView.ChartArea.DataSeries.Clear();
            radChartLine6.DefaultView.ChartArea.DataSeries.Clear();
            radChartLine7.DefaultView.ChartArea.DataSeries.Clear();
            radChartLine8.DefaultView.ChartArea.DataSeries.Clear();
            radChartLine9.DefaultView.ChartArea.DataSeries.Clear();
        }

        private void btnBuscar_Click(object sender, RoutedEventArgs e)
        {
            int ano = int.Parse(cboAno.SelectedValue.ToString());
            if (detalle.Where(x => x.year == ano).ToList().Count() == 0)
            {
                //hiddenRadChart();
                List<RGVCAFACII_Result> lista = new InfoTacticaDAO().getRGVCAFACII(ano, "1");//getReporteVentas(ano, "1");
                /*var buton = new Button();
                buton.Name = "button_" + ano;
                buton.Content = ano;
                buton.Height = 28;
                buton.VerticalAlignment = VerticalAlignment.Center;
                buton.Click += new RoutedEventHandler(b_Click);
                stkListaano.Children.Add(buton);*/


               /* foreach (var item in lista)
                {
                    //ACTUALIZAMOS SUCURSAL Y UNIDAD NEGOCIO
                    var sucur = new InfoTacticaDAO().getSucursal("1", item.CODUNI);
                    if (sucur != null)
                    {
                        item.CODUNI = sucur.ShortDesc;
                        //item.CODSUC = sucur.ShortDesc;
                    }
                }*/


                resumenProduccion d = new resumenProduccion { year = ano, detalle = new List<Produccion>() };
                foreach (var sucursal in lista.Select(x => x.CODUNI).Distinct())
                {
                    Produccion det = new Produccion { monto = Convert.ToDouble(lista.Where(x => x.CODUNI == sucursal).Sum(x => x.TOTRGVS.Value).ToString()), sede = sucursal };
                    d.detalle.Add(det);
                }
                resumen.Add(d);
                rpcTotal.DefaultView.ChartArea.DataSeries.Clear();
                foreach (var item in resumen)
                {
                    rpcTotal.DefaultView.ChartTitle.Content = "Resumen Ventas";
                    rpcTotal.DefaultView.ChartLegend.Header = "Leyenda";
                    rpcTotal.DefaultView.ChartLegend.UseAutoGeneratedItems = true;

                    rpcTotal.DefaultView.ChartArea.AxisX.Title = "Sede";
                    rpcTotal.DefaultView.ChartArea.AxisX.AutoRange = false;
                    rpcTotal.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Between;

                    rpcTotal.DefaultView.ChartArea.AxisX.MinValue = 1;
                    rpcTotal.DefaultView.ChartArea.AxisX.MaxValue = 8;
                    rpcTotal.DefaultView.ChartArea.AxisX.Step = 1;
                    rpcTotal.DefaultView.ChartArea.AxisY.Title = "Cantidad";

                    DataSeries series = new DataSeries();
                    series.Definition = new LineSeriesDefinition();
                    series.LegendLabel = item.year.ToString();
                    rpcTotal.DefaultSeriesDefinition.LegendDisplayMode = LegendDisplayMode.SeriesLabel;

                    series.Add(new DataPoint("Central", item.detalle.Where(x => x.sede.ToLower().StartsWith("central")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Piura", item.detalle.Where(x => x.sede.ToLower().StartsWith("piura")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Polaris", item.detalle.Where(x => x.sede.ToLower().StartsWith("polaris")).Sum(x => x.monto)));
                    series.Add(new DataPoint("SanJudas", item.detalle.Where(x => x.sede.ToLower().StartsWith("sanjudas")).Sum(x => x.monto)));
                    series.Add(new DataPoint("JavierPrado", item.detalle.Where(x => x.sede.ToLower().StartsWith("javierprado")).Sum(x => x.cantidad)));
                    series.Add(new DataPoint("Benavides", item.detalle.Where(x => x.sede.ToLower().StartsWith("benavides")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Golf", item.detalle.Where(x => x.sede.ToLower().StartsWith("golf")).Sum(x => x.monto)));
                    series.Add(new DataPoint("SanBorja", item.detalle.Where(x => x.sede.ToLower().StartsWith("sanborja")).Sum(x => x.monto)));

                    rpcTotal.DefaultView.ChartArea.DataSeries.Add(series);
                }


                foreach (var sede in lista.OrderBy(x => x.CODUNI).Select(x => x.CODUNI).Distinct())
                {
                    SedeProduccion item = new SedeProduccion();
                    item.sede = sede;
                    item.year = ano;
                    item.detalle = new List<ProduccionMensual>();
                    foreach (var mes in lista.Where(x => x.CODUNI == sede).Select(x => x.MES).Distinct())
                    {
                        item.detalle.Add(new ProduccionMensual { mes = mes, monto = Convert.ToDouble(lista.Where(x => x.CODUNI == sede && x.MES == mes).Sum(x => x.TOTRGVS).ToString()) });
                    }
                    detalle.Add(item);
                }
                setData(ano);
            }
        }

        private void b_Click(object sender, RoutedEventArgs e)
        {
            var current = sender as Button;
            //setData(int.Parse(current.Content.ToString()));
        }

        private void setData(int ano)
        {
            hiddenRadChart();

            foreach (var item in detalle.ToList())
            {
                if (item.sede == "Central")
                {
                    radChartLine.DefaultView.ChartTitle.Content = item.sede;
                    radChartLine.DefaultView.ChartLegend.Header = "Leyenda";
                    radChartLine.DefaultView.ChartLegend.UseAutoGeneratedItems = true;

                    radChartLine.DefaultView.ChartArea.AxisX.Title = "Mes";
                    radChartLine.DefaultView.ChartArea.AxisX.AutoRange = false;
                    radChartLine.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Between;
                    radChartLine.DefaultView.ChartArea.AxisX.MinValue = 1;
                    radChartLine.DefaultView.ChartArea.AxisX.MaxValue = 12;
                    radChartLine.DefaultView.ChartArea.AxisX.Step = 1;

                    radChartLine.DefaultView.ChartArea.AxisY.Title = "Cantidad";
                    DataSeries series = new DataSeries();
                    series.Definition = new LineSeriesDefinition();
                    series.LegendLabel = item.year.ToString();
                    radChartLine.DefaultSeriesDefinition.LegendDisplayMode = LegendDisplayMode.SeriesLabel;

                    series.Add(new DataPoint("Ene", item.detalle.Where(x => x.mes.StartsWith("Ene")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Feb", item.detalle.Where(x => x.mes.StartsWith("Feb")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Mar", item.detalle.Where(x => x.mes.StartsWith("Mar")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Abr", item.detalle.Where(x => x.mes.StartsWith("Abr")).Sum(x => x.monto)));
                    series.Add(new DataPoint("May", item.detalle.Where(x => x.mes.StartsWith("May")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jun", item.detalle.Where(x => x.mes.StartsWith("Jun")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jul", item.detalle.Where(x => x.mes.StartsWith("Jul")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Ago", item.detalle.Where(x => x.mes.StartsWith("Ago")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Sep", item.detalle.Where(x => x.mes.StartsWith("Sep")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Oct", item.detalle.Where(x => x.mes.StartsWith("Oct")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Nov", item.detalle.Where(x => x.mes.StartsWith("Nov")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Dic", item.detalle.Where(x => x.mes.StartsWith("Dic")).Sum(x => x.monto)));

                    radChartLine.DefaultView.ChartArea.DataSeries.Add(series);
                    radChartLine.Visibility = Visibility.Visible;
                }
                else if (item.sede == "Piura")
                {
                    radChartLine2.DefaultView.ChartTitle.Content = item.sede;
                    radChartLine2.DefaultView.ChartLegend.Header = "Leyenda";
                    radChartLine2.DefaultView.ChartLegend.UseAutoGeneratedItems = true;

                    radChartLine2.DefaultView.ChartArea.AxisX.Title = "Mes";
                    radChartLine2.DefaultView.ChartArea.AxisX.AutoRange = false;
                    radChartLine2.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Between;
                    radChartLine2.DefaultView.ChartArea.AxisX.MinValue = 1;
                    radChartLine2.DefaultView.ChartArea.AxisX.MaxValue = 12;
                    radChartLine2.DefaultView.ChartArea.AxisX.Step = 1;

                    radChartLine2.DefaultView.ChartArea.AxisY.Title = "Cantidad";
                    DataSeries series = new DataSeries();
                    series.Definition = new LineSeriesDefinition();
                    series.LegendLabel = item.year.ToString();
                    radChartLine2.DefaultSeriesDefinition.LegendDisplayMode = LegendDisplayMode.SeriesLabel;
                    series.Add(new DataPoint("Ene", item.detalle.Where(x => x.mes.StartsWith("Ene")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Feb", item.detalle.Where(x => x.mes.StartsWith("Feb")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Mar", item.detalle.Where(x => x.mes.StartsWith("Mar")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Abr", item.detalle.Where(x => x.mes.StartsWith("Abr")).Sum(x => x.monto)));
                    series.Add(new DataPoint("May", item.detalle.Where(x => x.mes.StartsWith("May")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jun", item.detalle.Where(x => x.mes.StartsWith("Jun")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jul", item.detalle.Where(x => x.mes.StartsWith("Jul")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Ago", item.detalle.Where(x => x.mes.StartsWith("Ago")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Sep", item.detalle.Where(x => x.mes.StartsWith("Sep")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Oct", item.detalle.Where(x => x.mes.StartsWith("Oct")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Nov", item.detalle.Where(x => x.mes.StartsWith("Nov")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Dic", item.detalle.Where(x => x.mes.StartsWith("Dic")).Sum(x => x.monto)));
                    radChartLine2.DefaultView.ChartArea.DataSeries.Add(series);
                    radChartLine2.Visibility = Visibility.Visible;
                }
                else if (item.sede == "Polaris")
                {
                    radChartLine3.DefaultView.ChartTitle.Content = item.sede;
                    radChartLine3.DefaultView.ChartLegend.Header = "Leyenda";
                    radChartLine3.DefaultView.ChartLegend.UseAutoGeneratedItems = true;

                    radChartLine3.DefaultView.ChartArea.AxisX.Title = "Mes";
                    radChartLine3.DefaultView.ChartArea.AxisX.AutoRange = false;
                    radChartLine3.DefaultView.ChartArea.AxisX.MinValue = 1;
                    radChartLine3.DefaultView.ChartArea.AxisX.MaxValue = 12;
                    radChartLine3.DefaultView.ChartArea.AxisX.Step = 1;
                    radChartLine3.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Between;

                    radChartLine3.DefaultView.ChartArea.AxisY.Title = "Cantidad";
                    DataSeries series = new DataSeries();
                    series.Definition = new LineSeriesDefinition();
                    series.LegendLabel = item.year.ToString();
                    radChartLine3.DefaultSeriesDefinition.LegendDisplayMode = LegendDisplayMode.SeriesLabel;
                    series.Add(new DataPoint("Ene", item.detalle.Where(x => x.mes.StartsWith("Ene")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Feb", item.detalle.Where(x => x.mes.StartsWith("Feb")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Mar", item.detalle.Where(x => x.mes.StartsWith("Mar")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Abr", item.detalle.Where(x => x.mes.StartsWith("Abr")).Sum(x => x.monto)));
                    series.Add(new DataPoint("May", item.detalle.Where(x => x.mes.StartsWith("May")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jun", item.detalle.Where(x => x.mes.StartsWith("Jun")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jul", item.detalle.Where(x => x.mes.StartsWith("Jul")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Ago", item.detalle.Where(x => x.mes.StartsWith("Ago")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Sep", item.detalle.Where(x => x.mes.StartsWith("Sep")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Oct", item.detalle.Where(x => x.mes.StartsWith("Oct")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Nov", item.detalle.Where(x => x.mes.StartsWith("Nov")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Dic", item.detalle.Where(x => x.mes.StartsWith("Dic")).Sum(x => x.monto)));
                    radChartLine3.DefaultView.ChartArea.DataSeries.Add(series);
                    radChartLine3.Visibility = Visibility.Visible;
                }
                else if (item.sede == "SanJudas")
                {
                    radChartLine4.DefaultView.ChartTitle.Content = item.sede;
                    radChartLine4.DefaultView.ChartLegend.Header = "Leyenda";
                    radChartLine4.DefaultView.ChartLegend.UseAutoGeneratedItems = true;

                    radChartLine4.DefaultView.ChartArea.AxisX.Title = "Mes";
                    radChartLine4.DefaultView.ChartArea.AxisX.AutoRange = false;
                    radChartLine4.DefaultView.ChartArea.AxisX.MinValue = 1;
                    radChartLine4.DefaultView.ChartArea.AxisX.MaxValue = 12;
                    radChartLine4.DefaultView.ChartArea.AxisX.Step = 1;
                    radChartLine4.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Between;

                    radChartLine4.DefaultView.ChartArea.AxisY.Title = "Cantidad";
                    DataSeries series = new DataSeries();
                    series.Definition = new LineSeriesDefinition();
                    series.LegendLabel = item.year.ToString();
                    radChartLine4.DefaultSeriesDefinition.LegendDisplayMode = LegendDisplayMode.SeriesLabel;
                    series.Add(new DataPoint("Ene", item.detalle.Where(x => x.mes.StartsWith("Ene")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Feb", item.detalle.Where(x => x.mes.StartsWith("Feb")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Mar", item.detalle.Where(x => x.mes.StartsWith("Mar")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Abr", item.detalle.Where(x => x.mes.StartsWith("Abr")).Sum(x => x.monto)));
                    series.Add(new DataPoint("May", item.detalle.Where(x => x.mes.StartsWith("May")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jun", item.detalle.Where(x => x.mes.StartsWith("Jun")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jul", item.detalle.Where(x => x.mes.StartsWith("Jul")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Ago", item.detalle.Where(x => x.mes.StartsWith("Ago")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Sep", item.detalle.Where(x => x.mes.StartsWith("Sep")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Oct", item.detalle.Where(x => x.mes.StartsWith("Oct")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Nov", item.detalle.Where(x => x.mes.StartsWith("Nov")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Dic", item.detalle.Where(x => x.mes.StartsWith("Dic")).Sum(x => x.monto)));
                    radChartLine4.DefaultView.ChartArea.DataSeries.Add(series);
                    radChartLine4.Visibility = Visibility.Visible;
                }
                else if (item.sede == "JavierPrado")
                {
                    radChartLine5.DefaultView.ChartTitle.Content = item.sede;
                    radChartLine5.DefaultView.ChartLegend.Header = "Leyenda";
                    radChartLine5.DefaultView.ChartLegend.UseAutoGeneratedItems = true;

                    radChartLine5.DefaultView.ChartArea.AxisX.Title = "Mes";
                    radChartLine5.DefaultView.ChartArea.AxisX.AutoRange = false;
                    radChartLine5.DefaultView.ChartArea.AxisX.MinValue = 1;
                    radChartLine5.DefaultView.ChartArea.AxisX.MaxValue = 12;
                    radChartLine5.DefaultView.ChartArea.AxisX.Step = 1;
                    radChartLine5.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Between;

                    radChartLine5.DefaultView.ChartArea.AxisY.Title = "Cantidad";
                    DataSeries series = new DataSeries();
                    series.Definition = new LineSeriesDefinition();
                    series.LegendLabel = item.year.ToString();
                    radChartLine5.DefaultSeriesDefinition.LegendDisplayMode = LegendDisplayMode.SeriesLabel;
                    series.Add(new DataPoint("Ene", item.detalle.Where(x => x.mes.StartsWith("Ene")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Feb", item.detalle.Where(x => x.mes.StartsWith("Feb")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Mar", item.detalle.Where(x => x.mes.StartsWith("Mar")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Abr", item.detalle.Where(x => x.mes.StartsWith("Abr")).Sum(x => x.monto)));
                    series.Add(new DataPoint("May", item.detalle.Where(x => x.mes.StartsWith("May")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jun", item.detalle.Where(x => x.mes.StartsWith("Jun")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jul", item.detalle.Where(x => x.mes.StartsWith("Jul")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Ago", item.detalle.Where(x => x.mes.StartsWith("Ago")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Sep", item.detalle.Where(x => x.mes.StartsWith("Sep")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Oct", item.detalle.Where(x => x.mes.StartsWith("Oct")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Nov", item.detalle.Where(x => x.mes.StartsWith("Nov")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Dic", item.detalle.Where(x => x.mes.StartsWith("Dic")).Sum(x => x.monto)));
                    radChartLine5.DefaultView.ChartArea.DataSeries.Add(series);
                    radChartLine5.Visibility = Visibility.Visible;
                }
                else if (item.sede == "Benavides")
                {
                    radChartLine6.DefaultView.ChartTitle.Content = item.sede;
                    radChartLine6.DefaultView.ChartLegend.Header = "Leyenda";
                    radChartLine6.DefaultView.ChartLegend.UseAutoGeneratedItems = true;

                    radChartLine6.DefaultView.ChartArea.AxisX.Title = "Mes";
                    radChartLine6.DefaultView.ChartArea.AxisX.AutoRange = false;
                    radChartLine6.DefaultView.ChartArea.AxisX.MinValue = 1;
                    radChartLine6.DefaultView.ChartArea.AxisX.MaxValue = 12;
                    radChartLine6.DefaultView.ChartArea.AxisX.Step = 1;
                    radChartLine6.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Between;

                    radChartLine6.DefaultView.ChartArea.AxisY.Title = "Cantidad";
                    DataSeries series = new DataSeries();
                    series.Definition = new LineSeriesDefinition();
                    series.LegendLabel = item.year.ToString();
                    radChartLine6.DefaultSeriesDefinition.LegendDisplayMode = LegendDisplayMode.SeriesLabel;
                    series.Add(new DataPoint("Ene", item.detalle.Where(x => x.mes.StartsWith("Ene")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Feb", item.detalle.Where(x => x.mes.StartsWith("Feb")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Mar", item.detalle.Where(x => x.mes.StartsWith("Mar")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Abr", item.detalle.Where(x => x.mes.StartsWith("Abr")).Sum(x => x.monto)));
                    series.Add(new DataPoint("May", item.detalle.Where(x => x.mes.StartsWith("May")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jun", item.detalle.Where(x => x.mes.StartsWith("Jun")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jul", item.detalle.Where(x => x.mes.StartsWith("Jul")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Ago", item.detalle.Where(x => x.mes.StartsWith("Ago")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Sep", item.detalle.Where(x => x.mes.StartsWith("Sep")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Oct", item.detalle.Where(x => x.mes.StartsWith("Oct")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Nov", item.detalle.Where(x => x.mes.StartsWith("Nov")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Dic", item.detalle.Where(x => x.mes.StartsWith("Dic")).Sum(x => x.monto)));
                    radChartLine6.DefaultView.ChartArea.DataSeries.Add(series);
                    radChartLine6.Visibility = Visibility.Visible;
                }
                else if (item.sede == "Golf")
                {
                    radChartLine7.DefaultView.ChartTitle.Content = item.sede;
                    radChartLine7.DefaultView.ChartLegend.Header = "Leyenda";
                    radChartLine7.DefaultView.ChartLegend.UseAutoGeneratedItems = true;

                    radChartLine7.DefaultView.ChartArea.AxisX.Title = "Mes";
                    radChartLine7.DefaultView.ChartArea.AxisX.AutoRange = false;
                    radChartLine7.DefaultView.ChartArea.AxisX.MinValue = 1;
                    radChartLine7.DefaultView.ChartArea.AxisX.MaxValue = 12;
                    radChartLine7.DefaultView.ChartArea.AxisX.Step = 1;
                    radChartLine7.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Between;

                    radChartLine7.DefaultView.ChartArea.AxisY.Title = "Cantidad";
                    DataSeries series = new DataSeries();
                    series.Definition = new LineSeriesDefinition();
                    series.LegendLabel = item.year.ToString();
                    radChartLine7.DefaultSeriesDefinition.LegendDisplayMode = LegendDisplayMode.SeriesLabel;
                    series.Add(new DataPoint("Ene", item.detalle.Where(x => x.mes.StartsWith("Ene")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Feb", item.detalle.Where(x => x.mes.StartsWith("Feb")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Mar", item.detalle.Where(x => x.mes.StartsWith("Mar")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Abr", item.detalle.Where(x => x.mes.StartsWith("Abr")).Sum(x => x.monto)));
                    series.Add(new DataPoint("May", item.detalle.Where(x => x.mes.StartsWith("May")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jun", item.detalle.Where(x => x.mes.StartsWith("Jun")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jul", item.detalle.Where(x => x.mes.StartsWith("Jul")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Ago", item.detalle.Where(x => x.mes.StartsWith("Ago")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Sep", item.detalle.Where(x => x.mes.StartsWith("Sep")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Oct", item.detalle.Where(x => x.mes.StartsWith("Oct")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Nov", item.detalle.Where(x => x.mes.StartsWith("Nov")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Dic", item.detalle.Where(x => x.mes.StartsWith("Dic")).Sum(x => x.monto)));
                    radChartLine7.DefaultView.ChartArea.DataSeries.Add(series);
                    radChartLine7.Visibility = Visibility.Visible;
                }
                else if (item.sede == "SanBorja")
                {
                    radChartLine8.DefaultView.ChartTitle.Content = item.sede;
                    radChartLine8.DefaultView.ChartLegend.Header = "Leyenda";
                    radChartLine8.DefaultView.ChartLegend.UseAutoGeneratedItems = true;

                    radChartLine8.DefaultView.ChartArea.AxisX.Title = "Mes";
                    radChartLine8.DefaultView.ChartArea.AxisX.AutoRange = false;
                    radChartLine8.DefaultView.ChartArea.AxisX.MinValue = 1;
                    radChartLine8.DefaultView.ChartArea.AxisX.MaxValue = 12;
                    radChartLine8.DefaultView.ChartArea.AxisX.Step = 1;
                    radChartLine8.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Between;

                    radChartLine8.DefaultView.ChartArea.AxisY.Title = "Cantidad";
                    DataSeries series = new DataSeries();
                    series.Definition = new LineSeriesDefinition();
                    series.LegendLabel = item.year.ToString();
                    radChartLine8.DefaultSeriesDefinition.LegendDisplayMode = LegendDisplayMode.SeriesLabel;
                    series.Add(new DataPoint("Ene", item.detalle.Where(x => x.mes.StartsWith("Ene")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Feb", item.detalle.Where(x => x.mes.StartsWith("Feb")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Mar", item.detalle.Where(x => x.mes.StartsWith("Mar")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Abr", item.detalle.Where(x => x.mes.StartsWith("Abr")).Sum(x => x.monto)));
                    series.Add(new DataPoint("May", item.detalle.Where(x => x.mes.StartsWith("May")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jun", item.detalle.Where(x => x.mes.StartsWith("Jun")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jul", item.detalle.Where(x => x.mes.StartsWith("Jul")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Ago", item.detalle.Where(x => x.mes.StartsWith("Ago")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Sep", item.detalle.Where(x => x.mes.StartsWith("Sep")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Oct", item.detalle.Where(x => x.mes.StartsWith("Oct")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Nov", item.detalle.Where(x => x.mes.StartsWith("Nov")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Dic", item.detalle.Where(x => x.mes.StartsWith("Dic")).Sum(x => x.monto)));
                    radChartLine8.DefaultView.ChartArea.DataSeries.Add(series);
                    radChartLine8.Visibility = Visibility.Visible;
                }
                else if (item.sede == "-")
                {
                    radChartLine9.DefaultView.ChartTitle.Content = item.sede;
                    radChartLine9.DefaultView.ChartLegend.Header = "Leyenda";
                    radChartLine9.DefaultView.ChartLegend.UseAutoGeneratedItems = true;

                    radChartLine9.DefaultView.ChartArea.AxisX.Title = "Mes";
                    radChartLine9.DefaultView.ChartArea.AxisX.AutoRange = false;
                    radChartLine9.DefaultView.ChartArea.AxisX.MinValue = 1;
                    radChartLine9.DefaultView.ChartArea.AxisX.MaxValue = 12;
                    radChartLine9.DefaultView.ChartArea.AxisX.Step = 1;
                    radChartLine9.DefaultView.ChartArea.AxisX.LayoutMode = AxisLayoutMode.Between;

                    radChartLine9.DefaultView.ChartArea.AxisY.Title = "Cantidad";
                    DataSeries series = new DataSeries();
                    series.Definition = new LineSeriesDefinition();
                    series.LegendLabel = item.year.ToString();
                    radChartLine9.DefaultSeriesDefinition.LegendDisplayMode = LegendDisplayMode.SeriesLabel;
                    series.Add(new DataPoint("Ene", item.detalle.Where(x => x.mes.StartsWith("Ene")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Feb", item.detalle.Where(x => x.mes.StartsWith("Feb")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Mar", item.detalle.Where(x => x.mes.StartsWith("Mar")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Abr", item.detalle.Where(x => x.mes.StartsWith("Abr")).Sum(x => x.monto)));
                    series.Add(new DataPoint("May", item.detalle.Where(x => x.mes.StartsWith("May")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jun", item.detalle.Where(x => x.mes.StartsWith("Jun")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Jul", item.detalle.Where(x => x.mes.StartsWith("Jul")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Ago", item.detalle.Where(x => x.mes.StartsWith("Ago")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Sep", item.detalle.Where(x => x.mes.StartsWith("Sep")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Oct", item.detalle.Where(x => x.mes.StartsWith("Oct")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Nov", item.detalle.Where(x => x.mes.StartsWith("Nov")).Sum(x => x.monto)));
                    series.Add(new DataPoint("Dic", item.detalle.Where(x => x.mes.StartsWith("Dic")).Sum(x => x.monto)));
                    radChartLine9.DefaultView.ChartArea.DataSeries.Add(series);
                    radChartLine9.Visibility = Visibility.Visible;
                }
            }

        }
    }
}
