//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_Stock_Item
    {
        public int AL_Stock_ItemID { get; set; }
        public int AL_Stock_InID { get; set; }
        public string CodeBar { get; set; }
        public int Correlativo { get; set; }
        public System.DateTime AuFecReg { get; set; }
        public string AuUsuReg { get; set; }
        public int AL_InsumId { get; set; }
        public int AL_AlmacenId { get; set; }
        public System.DateTime FecIngreso { get; set; }
        public Nullable<System.DateTime> FecVencimiento { get; set; }
        public Nullable<int> AL_Stock_ConsumoID { get; set; }
        public Nullable<int> AL_Stock_MoveID { get; set; }
    
        public virtual AL_Almacen AL_Almacen { get; set; }
        public virtual AL_Insum AL_Insum { get; set; }
    }
}
