//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGOINFORMES
    {
        public int numeroestudio { get; set; }
        public int codigopaciente { get; set; }
        public string codigoestudio { get; set; }
        public int codigocompaniaseguro { get; set; }
        public System.DateTime fechaimprime { get; set; }
        public string codigousuario { get; set; }
        public string recepciona { get; set; }
        public System.DateTime fechaentrega { get; set; }
        public string estadocargo { get; set; }
        public string usuRecepciona { get; set; }
        public string usuDescarga { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
