//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBRANZACIASEGURO
    {
        public string numerodocumento { get; set; }
        public string ruc { get; set; }
        public int codigopaciente { get; set; }
        public string codigousuario { get; set; }
        public int numeroatencion { get; set; }
        public System.DateTime fechaemision { get; set; }
        public Nullable<System.DateTime> fecharecepcion { get; set; }
        public Nullable<System.DateTime> fechacancelacion { get; set; }
        public string estado { get; set; }
        public Nullable<int> numerodelote { get; set; }
        public string codigotipoperacion { get; set; }
        public Nullable<System.DateTime> fechadescargo { get; set; }
        public string cuentacontable { get; set; }
        public Nullable<int> numeromovimiento { get; set; }
        public Nullable<bool> IsExoneradoTrama { get; set; }
    
        public virtual DOCUMENTO DOCUMENTO { get; set; }
    }
}
