//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Com_Medico
    {
        public int idCom_Medico { get; set; }
        public string medico { get; set; }
        public Nullable<decimal> com_asegurado { get; set; }
        public Nullable<decimal> com_particulares { get; set; }
        public Nullable<decimal> com_almenara { get; set; }
        public Nullable<decimal> com_Sabogal { get; set; }
        public Nullable<bool> isActivo { get; set; }
        public string email { get; set; }
        public string codigousuario { get; set; }
    }
}
