//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANIASEGURO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPANIASEGURO()
        {
            this.ESTUDIO_COMPANIA = new HashSet<ESTUDIO_COMPANIA>();
            this.CITA = new HashSet<CITA>();
            this.CARTAGARANTIA = new HashSet<CARTAGARANTIA>();
        }
    
        public int codigocompaniaseguro { get; set; }
        public string ruc { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> IsAgrupable { get; set; }
        public Nullable<bool> IsRequested { get; set; }
        public Nullable<bool> IsSCTR { get; set; }
        public Nullable<bool> IsAp { get; set; }
        public Nullable<bool> IsObsolet { get; set; }
        public Nullable<int> GrupoId { get; set; }
        public string correo_facturacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTUDIO_COMPANIA> ESTUDIO_COMPANIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITA> CITA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTAGARANTIA> CARTAGARANTIA { get; set; }
        public virtual ASEGURADORA ASEGURADORA { get; set; }
    }
}
