//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleResultadoDelivery
    {
        public int idDetResultado { get; set; }
        public int idResultado { get; set; }
        public int examen { get; set; }
        public int placas { get; set; }
        public int fotos { get; set; }
    }
}
