//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBROCAJA
    {
        public int numerodocumento { get; set; }
        public int numeroatencion { get; set; }
        public Nullable<int> codigopaciente { get; set; }
        public string cmp { get; set; }
        public Nullable<int> numerocita { get; set; }
        public Nullable<int> codigocompaniaseguro { get; set; }
        public string ruc { get; set; }
        public float descuento { get; set; }
        public float total { get; set; }
        public float igv { get; set; }
        public float subtotal { get; set; }
        public float pagoneto { get; set; }
        public float saldo { get; set; }
        public string observacion { get; set; }
        public bool cortesia { get; set; }
        public System.DateTime fechacobranza { get; set; }
        public string turno { get; set; }
        public string terminopago { get; set; }
        public Nullable<int> codigomodalidad { get; set; }
        public Nullable<int> codigounidad { get; set; }
        public string codigousuario { get; set; }
        public string formaentrega { get; set; }
        public string lugarentrega { get; set; }
        public Nullable<int> codigosucursal { get; set; }
        public string numerodocumento2 { get; set; }
    
        public virtual ATENCION ATENCION { get; set; }
    }
}
