//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReporteContabilidad
    {
        public Nullable<System.DateTime> fechayhora { get; set; }
        public int codigo { get; set; }
        public string paciente { get; set; }
        public Nullable<int> codigopaciente { get; set; }
        public string nombreestudio { get; set; }
        public string codigoestudio { get; set; }
        public string modalidad { get; set; }
        public string encuestador { get; set; }
        public string supervisor { get; set; }
        public string tecnologo { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> valor_tecnologo { get; set; }
        public string equipo { get; set; }
        public string tipoEstudioTecnologo { get; set; }
    }
}
