//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKT_Counter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TKT_Counter()
        {
            this.TKT_Historial = new HashSet<TKT_Historial>();
            this.TKT_Historial1 = new HashSet<TKT_Historial>();
            this.TKT_List_Atencion = new HashSet<TKT_List_Atencion>();
            this.TKT_Ticketera = new HashSet<TKT_Ticketera>();
        }
    
        public int idcounter { get; set; }
        public string nombre { get; set; }
        public bool isActivo { get; set; }
        public Nullable<int> idSede { get; set; }
        public bool isEliminado { get; set; }
        public int idempresa { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKT_Historial> TKT_Historial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKT_Historial> TKT_Historial1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKT_List_Atencion> TKT_List_Atencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKT_Ticketera> TKT_Ticketera { get; set; }
    }
}
