//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_Insum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AL_Insum()
        {
            this.AL_Stock_Diario = new HashSet<AL_Stock_Diario>();
            this.AL_Stock_Current = new HashSet<AL_Stock_Current>();
            this.AL_Stock_Item = new HashSet<AL_Stock_Item>();
        }
    
        public int Al_InsumId { get; set; }
        public Nullable<int> IN_SubClaseId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Correlativo { get; set; }
        public bool IsActive { get; set; }
        public string Comentario { get; set; }
        public string CorrelativoPref { get; set; }
        public Nullable<int> Concentracion { get; set; }
        public int ConcentracionUM { get; set; }
        public Nullable<decimal> Volumen { get; set; }
        public Nullable<int> VolumenUM { get; set; }
        public Nullable<decimal> PrecioByUnidad { get; set; }
        public Nullable<bool> IsInventario { get; set; }
        public int AL_TipoEspecifidadConsumoId { get; set; }
        public Nullable<int> UnidadBasicaUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AL_Stock_Diario> AL_Stock_Diario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AL_Stock_Current> AL_Stock_Current { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AL_Stock_Item> AL_Stock_Item { get; set; }
        public virtual AL_Insum AL_Insum1 { get; set; }
        public virtual AL_Insum AL_Insum2 { get; set; }
    }
}
