//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_Stock_Current
    {
        public int AL_Stock_CurrentID { get; set; }
        public int AlmacenId { get; set; }
        public int InsumoId { get; set; }
        public int CantActual { get; set; }
        public System.DateTime AuFecReg { get; set; }
        public string AuUsuReg { get; set; }
    
        public virtual AL_Almacen AL_Almacen { get; set; }
        public virtual AL_Insum AL_Insum { get; set; }
    }
}
