//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CG_SolicitudCarta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CG_SolicitudCarta()
        {
            this.CG_SolicituCarta_Historial = new HashSet<CG_SolicituCarta_Historial>();
        }
    
        public int idSolicitud { get; set; }
        public Nullable<int> idpaciente { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string num_doc { get; set; }
        public string email { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<int> celular { get; set; }
        public Nullable<int> idAseguradora { get; set; }
        public string aseguradora { get; set; }
        public string nombre_medico { get; set; }
        public string clinica { get; set; }
        public string idAdjunto { get; set; }
        public string comentario { get; set; }
        public int estado { get; set; }
        public Nullable<System.DateTime> fec_registro { get; set; }
        public Nullable<System.DateTime> fec_lectura { get; set; }
        public string usu_lectura { get; set; }
        public string apellido_medico { get; set; }
        public Nullable<int> numeroproforma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CG_SolicituCarta_Historial> CG_SolicituCarta_Historial { get; set; }
    }
}
