//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLINICAHOSPITAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLINICAHOSPITAL()
        {
            this.CITA = new HashSet<CITA>();
        }
    
        public int codigoclinica { get; set; }
        public string razonsocial { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public string web { get; set; }
        public int codigozona { get; set; }
        public string tipo { get; set; }
        public Nullable<int> IdIpress { get; set; }
        public string CodigoIpress { get; set; }
        public string UbigeoId { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string rucClinica { get; set; }
        public Nullable<System.DateTime> AuFecNew { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<System.DateTime> AuFecUpd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITA> CITA { get; set; }
    }
}
