//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEDOCUMENTO
    {
        public int codigodetalle { get; set; }
        public string numerodocumento { get; set; }
        public string ruc { get; set; }
        public int codigopaciente { get; set; }
        public string codigousuario { get; set; }
        public string descripcion { get; set; }
        public string codigoestudio { get; set; }
        public int codigocompaniaseguro { get; set; }
        public float valorventa { get; set; }
        public int codigoclase { get; set; }
        public int codigomodalidad { get; set; }
        public int codigounidad { get; set; }
        public decimal desc_cortesia { get; set; }
        public decimal desc_carta { get; set; }
        public decimal desc_promociones { get; set; }
        public decimal preciounitario { get; set; }
        public int cantidad { get; set; }
        public decimal porDesPromo { get; set; }
        public decimal porDesCarta { get; set; }
        public decimal porDescuento { get; set; }
        public int tipoIGV { get; set; }
        public decimal valorigv { get; set; }
    
        public virtual ESTUDIO_COMPANIA ESTUDIO_COMPANIA { get; set; }
        public virtual DOCUMENTO DOCUMENTO { get; set; }
    }
}
