//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO_ESTUDIO
    {
        public int codigoequipo { get; set; }
        public string codigoestudio { get; set; }
        public bool entreturno { get; set; }
        public bool bloqueado { get; set; }
        public string hora1 { get; set; }
        public string hora2 { get; set; }
        public bool acepta { get; set; }
        public int codigoclase { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual ESTUDIO ESTUDIO { get; set; }
    }
}
