//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIPO()
        {
            this.EQUIPO_ESTUDIO = new HashSet<EQUIPO_ESTUDIO>();
            this.EXAMENXATENCION = new HashSet<EXAMENXATENCION>();
            this.EXAMENXATENCION1 = new HashSet<EXAMENXATENCION>();
            this.HORARIO = new HashSet<HORARIO>();
            this.EXAMENXCITA = new HashSet<EXAMENXCITA>();
        }
    
        public System.DateTime fechaadquirio { get; set; }
        public float intensidad { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public string nombreequipo { get; set; }
        public int codigoequipo { get; set; }
        public int codigosucursal2 { get; set; }
        public int codigounidad2 { get; set; }
        public string estado { get; set; }
        public string ShortDesc { get; set; }
        public string LongDesc { get; set; }
        public Nullable<bool> isIntegrator { get; set; }
        public string PathTemplate { get; set; }
        public bool isSupervisable { get; set; }
        public Nullable<int> codigomodalidad2 { get; set; }
        public string EstadoActual { get; set; }
        public string AETitleConsulta { get; set; }
        public string StationName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPO_ESTUDIO> EQUIPO_ESTUDIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAMENXATENCION> EXAMENXATENCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAMENXATENCION> EXAMENXATENCION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIO> HORARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAMENXCITA> EXAMENXCITA { get; set; }
    }
}
