//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaGlobal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaGlobal()
        {
            this.DetalleFacturaGlobal = new HashSet<DetalleFacturaGlobal>();
        }
    
        public int idFac { get; set; }
        public string ruc { get; set; }
        public string aseguradora { get; set; }
        public System.DateTime fec_registro { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fec_documento { get; set; }
        public string numerodocumento { get; set; }
        public int empresa { get; set; }
        public string datosadicionales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaGlobal> DetalleFacturaGlobal { get; set; }
    }
}
