//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMADEPAGO
    {
        public int codigoformapago { get; set; }
        public float monto { get; set; }
        public int codigomodalidadpago { get; set; }
        public int codigomoneda { get; set; }
        public string numerodocumento { get; set; }
        public string ruc { get; set; }
        public int codigopaciente { get; set; }
        public string codigousuario { get; set; }
        public Nullable<int> codigotarjeta { get; set; }
        public Nullable<System.DateTime> fechadepago { get; set; }
        public Nullable<int> codigounidad { get; set; }
        public Nullable<int> codigosucursal { get; set; }
        public string numeroReferencia { get; set; }
    
        public virtual TARJETA TARJETA { get; set; }
        public virtual MONEDA MONEDA { get; set; }
        public virtual DOCUMENTO DOCUMENTO { get; set; }
    }
}
