//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESULTADODELIVERY
    {
        public int numerodelivery { get; set; }
        public int numeroatencion { get; set; }
        public int codigopaciente { get; set; }
        public string direcciondelivery { get; set; }
        public string personacontacto { get; set; }
        public string telefonodelivery { get; set; }
        public Nullable<int> codigodistrito { get; set; }
        public Nullable<int> codigozona { get; set; }
        public int cantidadplaca { get; set; }
        public int cantidadfoto { get; set; }
        public bool entregado { get; set; }
        public System.DateTime fechasalida { get; set; }
        public string observacion { get; set; }
        public System.DateTime horasalida { get; set; }
        public string tipoentrega { get; set; }
        public string codigousuario { get; set; }
        public byte[] firma { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
