//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Entre_Turno
    {
        public int IdSolicitud { get; set; }
        public System.DateTime fecha_reg { get; set; }
        public System.DateTime hora_reg { get; set; }
        public string usu_reg { get; set; }
        public int codigoequipo_reg { get; set; }
        public string solicitante { get; set; }
        public int codigomotivo { get; set; }
        public string comentario_usu { get; set; }
        public string usu_med { get; set; }
        public Nullable<System.DateTime> hora_med { get; set; }
        public string comentario_med { get; set; }
        public Nullable<System.DateTime> fec_aprueba { get; set; }
        public Nullable<bool> isaprobado { get; set; }
        public Nullable<int> codigoequipo_med { get; set; }
    
        public virtual Motivo_Entre_Turno Motivo_Entre_Turno { get; set; }
    }
}
