//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sunasa_Cobertura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sunasa_Cobertura()
        {
            this.CARTAGARANTIA = new HashSet<CARTAGARANTIA>();
        }
    
        public int Sunasa_CoberturaId { get; set; }
        public string Tipo { get; set; }
        public string Subtipo { get; set; }
        public string Nombre { get; set; }
        public string CodigoSited { get; set; }
        public bool IsActive { get; set; }
        public int codigocompaniaseguro { get; set; }
        public string NombreSuSalud { get; set; }
        public string CodigoSited2 { get; set; }
        public string TipoDescripcion { get; set; }
        public Nullable<int> SitedProductoId { get; set; }
        public string SitedCodigoTedef { get; set; }
        public Nullable<bool> IsBloqueado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTAGARANTIA> CARTAGARANTIA { get; set; }
    }
}
