//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resocentro_Desktop.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.SUCURSALXUSUARIO = new HashSet<SUCURSALXUSUARIO>();
            this.AUDITORIA_CARTAS_GARANTIA = new HashSet<AUDITORIA_CARTAS_GARANTIA>();
            this.CARTAGARANTIA = new HashSet<CARTAGARANTIA>();
            this.CARTAGARANTIA1 = new HashSet<CARTAGARANTIA>();
            this.CARTAGARANTIA2 = new HashSet<CARTAGARANTIA>();
            this.RESULTADODELIVERY = new HashSet<RESULTADODELIVERY>();
            this.RESULTADODELIVERY1 = new HashSet<RESULTADODELIVERY>();
            this.DOCUMENTO = new HashSet<DOCUMENTO>();
            this.TKT_Counter = new HashSet<TKT_Counter>();
        }
    
        public int jerarquia { get; set; }
        public string estadousuario { get; set; }
        public string siglas { get; set; }
        public string codigousuario { get; set; }
        public string dni { get; set; }
        public bool bloqueado { get; set; }
        public string contrasena { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> isEnf { get; set; }
        public Nullable<bool> isAnes { get; set; }
        public string username { get; set; }
        public string Acro { get; set; }
        public Nullable<int> CurrentUnidad { get; set; }
        public bool isSessionLocked { get; set; }
        public string User_Uid { get; set; }
        public Nullable<int> AreaId { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUCURSALXUSUARIO> SUCURSALXUSUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDITORIA_CARTAS_GARANTIA> AUDITORIA_CARTAS_GARANTIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTAGARANTIA> CARTAGARANTIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTAGARANTIA> CARTAGARANTIA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTAGARANTIA> CARTAGARANTIA2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTADODELIVERY> RESULTADODELIVERY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTADODELIVERY> RESULTADODELIVERY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO> DOCUMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TKT_Counter> TKT_Counter { get; set; }
    }
}
