//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjuntoIncidente
    {
        public int idAdjunto { get; set; }
        public int idIncidente { get; set; }
        public Nullable<int> idRevision { get; set; }
        public string pathFile { get; set; }
        public System.DateTime fecha_upload { get; set; }
        public string usuario { get; set; }
    }
}
