//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AL_Insum
    {
        public int Al_InsumId { get; set; }
        public Nullable<int> IN_SubClaseId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Correlativo { get; set; }
        public string CorrelativoPref { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> Volumen { get; set; }
        public Nullable<int> VolumenUM { get; set; }
        public Nullable<decimal> Concentracion { get; set; }
        public int ConcentracionUM { get; set; }
        public Nullable<decimal> PrecioByUnidad { get; set; }
        public string Comentario { get; set; }
        public Nullable<bool> IsInventario { get; set; }
        public int AL_TipoEspecifidadConsumoId { get; set; }
        public Nullable<int> UnidadBasicaUM { get; set; }
    
        public virtual AL_Insum AL_Insum1 { get; set; }
        public virtual AL_Insum AL_Insum2 { get; set; }
    }
}
