//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicativo
    {
        public Aplicativo()
        {
            this.Notificaciones = new HashSet<Notificaciones>();
            this.Permiso = new HashSet<Permiso>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Notificaciones> Notificaciones { get; set; }
        public virtual ICollection<Permiso> Permiso { get; set; }
    }
}
