//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion_Paciente
    {
        public int idCalificacion { get; set; }
        public int numeroatencion { get; set; }
        public int p1 { get; set; }
        public int p2 { get; set; }
        public int p3 { get; set; }
        public int p4 { get; set; }
        public int p5 { get; set; }
        public int p6 { get; set; }
        public int p7 { get; set; }
        public int p8 { get; set; }
        public System.DateTime fecha { get; set; }
        public string p1_1 { get; set; }
        public string p2_1 { get; set; }
        public string p3_1 { get; set; }
        public string p4_1 { get; set; }
        public string p5_1 { get; set; }
        public string p6_1 { get; set; }
        public string p7_1 { get; set; }
        public string p8_1 { get; set; }
    }
}
