//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANIASEGURO
    {
        public COMPANIASEGURO()
        {
            this.ESTUDIO_COMPANIA = new HashSet<ESTUDIO_COMPANIA>();
            this.CARTAGARANTIA = new HashSet<CARTAGARANTIA>();
            this.CITA = new HashSet<CITA>();
        }
    
        public int codigocompaniaseguro { get; set; }
        public string ruc { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> IsAgrupable { get; set; }
        public Nullable<bool> IsRequested { get; set; }
        public Nullable<bool> IsSCTR { get; set; }
        public Nullable<bool> IsAp { get; set; }
        public Nullable<bool> IsObsolet { get; set; }
        public Nullable<int> GrupoId { get; set; }
        public string correo_facturacion { get; set; }
    
        public virtual ICollection<ESTUDIO_COMPANIA> ESTUDIO_COMPANIA { get; set; }
        public virtual ICollection<CARTAGARANTIA> CARTAGARANTIA { get; set; }
        public virtual ICollection<CITA> CITA { get; set; }
    }
}
