//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo_PostProceso
    {
        public int codigoequipo { get; set; }
        public string nombreequipo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<System.DateTime> fechaadquirio { get; set; }
        public int codigosucursal { get; set; }
        public int codigounidad1 { get; set; }
        public string estado { get; set; }
    }
}
