//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCANADMISION
    {
        public int numerodeatencion { get; set; }
        public string nombrearchivo { get; set; }
        public byte[] cuerpoarchivo { get; set; }
        public System.DateTime fecharegistro { get; set; }
        public string codigousuario { get; set; }
    }
}
