//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudio_PostProceso
    {
        public int codigoestudio { get; set; }
        public string nombreestudio { get; set; }
        public string indicacion { get; set; }
        public Nullable<int> modalidad { get; set; }
        public Nullable<int> duracion { get; set; }
        public Nullable<decimal> factor { get; set; }
        public Nullable<int> clase { get; set; }
    }
}
