//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIO_COMPANIA
    {
        public string codigoestudio { get; set; }
        public int codigocompaniaseguro { get; set; }
        public string ruc { get; set; }
        public float precioreal { get; set; }
        public float preciobruto { get; set; }
        public int codigoclase { get; set; }
        public int codigomodalidad { get; set; }
        public int codigounidad { get; set; }
        public int codigomoneda { get; set; }
    
        public virtual COMPANIASEGURO COMPANIASEGURO { get; set; }
        public virtual ESTUDIO ESTUDIO { get; set; }
    }
}
