//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventosImpax
    {
        public int EventoImgId { get; set; }
        public int atencion { get; set; }
        public string TecnoFin { get; set; }
        public Nullable<System.DateTime> TecnoFecFin { get; set; }
        public string TecnoFinNotas { get; set; }
    }
}
