//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamenXEvento
    {
        public int codigo { get; set; }
        public int EventoId { get; set; }
        public System.DateTime FecNew { get; set; }
        public string codigousuario { get; set; }
        public string Nota { get; set; }
        public string EstadoExamen { get; set; }
        public string TecnoReg { get; set; }
        public Nullable<System.DateTime> TecnoFecReg { get; set; }
        public string TecnoFin { get; set; }
        public Nullable<System.DateTime> TecnoFecFin { get; set; }
        public string TecnoFinNotas { get; set; }
        public string UsuRegTecnoReg { get; set; }
    }
}
