//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamenAmpliacion
    {
        public int ExamenAmpliacionId { get; set; }
        public int codigo { get; set; }
        public string AuUsuReg { get; set; }
        public System.DateTime AuFecReg { get; set; }
        public Nullable<int> AmpliCodigo { get; set; }
        public string AmpliMotivo { get; set; }
        public string AmpliMotivoTecnica { get; set; }
        public Nullable<int> AmpliEqui1 { get; set; }
        public Nullable<int> AmpliEqui2 { get; set; }
        public System.DateTime AmpliSoliFec { get; set; }
        public string AmpliSoliUsu { get; set; }
        public Nullable<System.DateTime> AmpliCancelFec { get; set; }
        public string AmpliCancelUsu { get; set; }
        public string estadoestudio { get; set; }
        public string EstadoAmpliacion { get; set; }
        public string AmpliCancelaMotivo { get; set; }
        public Nullable<int> MED_TipoAmpliacionId { get; set; }
        public Nullable<int> TiempoEstimado { get; set; }
    }
}
