//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMENXCITA
    {
        public int codigoexamencita { get; set; }
        public int numerocita { get; set; }
        public int codigopaciente { get; set; }
        public System.DateTime horacita { get; set; }
        public float precioestudio { get; set; }
        public int codigocompaniaseguro { get; set; }
        public string ruc { get; set; }
        public int codigoequipo { get; set; }
        public string codigoestudio { get; set; }
        public int codigoclase { get; set; }
        public int codigomodalidad { get; set; }
        public int codigounidad { get; set; }
        public string estadoestudio { get; set; }
        public int codigomoneda { get; set; }
        public string sedador { get; set; }
        public string usu_cancela { get; set; }
        public string motivo { get; set; }
        public string otros_motivos { get; set; }
        public Nullable<System.DateTime> fecha_cancela { get; set; }
        public Nullable<float> precioestudioFinal { get; set; }
        public Nullable<System.DateTime> AuFecReg { get; set; }
        public string AuUsuReg { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual ESTUDIO ESTUDIO { get; set; }
        public virtual CITA CITA { get; set; }
    }
}
