//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_CLINICA_HOMBRO
    {
        public int numeroexamen { get; set; }
        public Nullable<bool> p1 { get; set; }
        public Nullable<bool> p1_1 { get; set; }
        public Nullable<bool> p1_2 { get; set; }
        public Nullable<bool> p1_3 { get; set; }
        public Nullable<bool> p1_4 { get; set; }
        public Nullable<bool> p1_5 { get; set; }
        public Nullable<bool> p1_6 { get; set; }
        public bool p2 { get; set; }
        public Nullable<bool> p2_1 { get; set; }
        public string p3 { get; set; }
        public string p4_1 { get; set; }
        public Nullable<int> p4_2 { get; set; }
        public Nullable<bool> p4_3 { get; set; }
        public Nullable<bool> p5 { get; set; }
        public string p5_1 { get; set; }
        public Nullable<bool> p6 { get; set; }
        public string p6_1 { get; set; }
        public string p7 { get; set; }
        public Nullable<bool> p8 { get; set; }
        public string p8_1 { get; set; }
        public string p8_21 { get; set; }
        public Nullable<int> p8_22 { get; set; }
        public string p8_3 { get; set; }
        public string p8_4 { get; set; }
        public Nullable<bool> p9 { get; set; }
        public string p9_1 { get; set; }
        public string p9_21 { get; set; }
        public Nullable<int> p9_22 { get; set; }
        public string p9_3 { get; set; }
        public Nullable<bool> p10 { get; set; }
        public Nullable<int> p10_1 { get; set; }
        public string p10_11 { get; set; }
        public string p10_21 { get; set; }
        public Nullable<int> p10_22 { get; set; }
        public string p10_3 { get; set; }
        public Nullable<bool> p11 { get; set; }
        public Nullable<int> p11_1 { get; set; }
        public string p11_11 { get; set; }
        public Nullable<int> p11_2 { get; set; }
        public string p12A { get; set; }
        public bool p12Acheck { get; set; }
        public string p12B { get; set; }
        public bool p12Bcheck { get; set; }
        public string p13 { get; set; }
        public Nullable<int> p14 { get; set; }
        public Nullable<int> p14_1 { get; set; }
        public System.DateTime fec_reg { get; set; }
        public string usu_reg { get; set; }
        public string usu_ult_upd { get; set; }
        public Nullable<System.DateTime> fec_ult_upd { get; set; }
        public Nullable<bool> p1_7 { get; set; }
        public string p1_7_1 { get; set; }
        public string p4_3_1 { get; set; }
        public Nullable<int> p2_21 { get; set; }
        public Nullable<int> p2_22 { get; set; }
        public bool p15 { get; set; }
    }
}
