//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_CLINICA_ONCOLOGICO
    {
        public int numeroestudio { get; set; }
        public Nullable<bool> p1 { get; set; }
        public string p1_1 { get; set; }
        public Nullable<bool> p2 { get; set; }
        public Nullable<bool> p2_1 { get; set; }
        public Nullable<int> p2_1_1 { get; set; }
        public string p2_1_2 { get; set; }
        public string p2_2 { get; set; }
        public string p2_3 { get; set; }
        public Nullable<int> p3 { get; set; }
        public string p3_1 { get; set; }
        public Nullable<bool> p4 { get; set; }
        public string p4_1 { get; set; }
        public Nullable<bool> p5 { get; set; }
        public Nullable<bool> p5_1 { get; set; }
        public Nullable<int> p5_1_1 { get; set; }
        public string p5_1_2 { get; set; }
        public Nullable<bool> p5_2 { get; set; }
        public Nullable<int> p5_2_1 { get; set; }
        public string p5_2_2 { get; set; }
        public Nullable<bool> p5_3 { get; set; }
        public Nullable<int> p5_3_1 { get; set; }
        public string p5_3_2 { get; set; }
        public string p5_4 { get; set; }
        public Nullable<bool> p6 { get; set; }
        public Nullable<bool> p6_1 { get; set; }
        public Nullable<int> p6_2 { get; set; }
        public string p6_3 { get; set; }
        public Nullable<bool> p7 { get; set; }
        public Nullable<bool> p7_1 { get; set; }
        public Nullable<int> p7_2 { get; set; }
        public string p7_3 { get; set; }
        public Nullable<bool> p8 { get; set; }
        public Nullable<int> p8_1 { get; set; }
        public Nullable<int> p8_2 { get; set; }
        public string p8_3 { get; set; }
        public Nullable<int> p8_4 { get; set; }
        public string p8_5 { get; set; }
        public string p9 { get; set; }
        public string usu_reg { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public string usu_ult_upd { get; set; }
        public Nullable<System.DateTime> fec_ult_upd { get; set; }
        public bool p10 { get; set; }
    }
}
