//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_CLINICA_EXTREMIDAD
    {
        public int numeroexamen { get; set; }
        public Nullable<bool> p1 { get; set; }
        public string p1_1 { get; set; }
        public Nullable<bool> p2 { get; set; }
        public Nullable<bool> p3 { get; set; }
        public string p3_1 { get; set; }
        public string p4_1 { get; set; }
        public Nullable<int> p4_2 { get; set; }
        public Nullable<bool> p4_3 { get; set; }
        public Nullable<bool> p5 { get; set; }
        public string p5_1 { get; set; }
        public string p6 { get; set; }
        public string p7_1 { get; set; }
        public string p7 { get; set; }
        public string p8 { get; set; }
        public string p9 { get; set; }
        public bool p10 { get; set; }
        public string p10_1 { get; set; }
        public string p10_21 { get; set; }
        public Nullable<int> p10_22 { get; set; }
        public string p10_3 { get; set; }
        public string p10_4 { get; set; }
        public bool p11 { get; set; }
        public Nullable<int> p11_1 { get; set; }
        public string p11_11 { get; set; }
        public string p11_21 { get; set; }
        public Nullable<int> p11_22 { get; set; }
        public string p11_3 { get; set; }
        public bool p12 { get; set; }
        public Nullable<int> p12_1 { get; set; }
        public string p12_2 { get; set; }
        public Nullable<int> p12_3 { get; set; }
        public string p13A_1 { get; set; }
        public bool p13A_2 { get; set; }
        public string p13B_1 { get; set; }
        public bool p13B_2 { get; set; }
        public string p14_1 { get; set; }
        public bool p14_2 { get; set; }
        public string p15 { get; set; }
        public Nullable<int> p15_1 { get; set; }
        public string usu_reg { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public string usu_ult_upd { get; set; }
        public Nullable<System.DateTime> fec_ult_upd { get; set; }
        public string p4_3_1 { get; set; }
        public Nullable<bool> p1_0 { get; set; }
        public Nullable<bool> p1_2 { get; set; }
        public Nullable<bool> p1_3 { get; set; }
        public Nullable<bool> p1_4 { get; set; }
        public Nullable<bool> p1_5 { get; set; }
        public Nullable<bool> p2_1 { get; set; }
        public Nullable<bool> p2_2 { get; set; }
        public Nullable<bool> p2_3 { get; set; }
        public Nullable<bool> p2_4 { get; set; }
        public Nullable<bool> p2_5 { get; set; }
        public string p2_5_1 { get; set; }
        public bool p16 { get; set; }
    }
}
