//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_CLINICA_FIBROSCAN
    {
        public int numeroexamen { get; set; }
        public Nullable<int> p1 { get; set; }
        public Nullable<bool> p2_1 { get; set; }
        public Nullable<bool> p2_2 { get; set; }
        public Nullable<bool> p2_3 { get; set; }
        public Nullable<bool> p2_4 { get; set; }
        public Nullable<bool> p3 { get; set; }
        public Nullable<bool> p4 { get; set; }
        public Nullable<bool> p5 { get; set; }
        public Nullable<int> p6 { get; set; }
        public Nullable<bool> p7_1 { get; set; }
        public Nullable<bool> p7_2 { get; set; }
        public Nullable<bool> p7_3 { get; set; }
        public Nullable<bool> p7_4 { get; set; }
        public string p7_4_1 { get; set; }
        public Nullable<bool> p8_1 { get; set; }
        public Nullable<bool> p8_2 { get; set; }
        public Nullable<bool> p8_3 { get; set; }
        public Nullable<bool> p8_4 { get; set; }
        public string p9 { get; set; }
        public string usu_reg { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public string usu_ult_upd { get; set; }
        public Nullable<System.DateTime> fec_ult_upd { get; set; }
    }
}
