//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_CLINICA_COLUMNA_C
    {
        public int numeroexamen { get; set; }
        public bool mol_p1 { get; set; }
        public Nullable<bool> mol_p1_1 { get; set; }
        public Nullable<bool> mol_p1_2 { get; set; }
        public Nullable<bool> mol_p1_3 { get; set; }
        public string mol_p1_3_1 { get; set; }
        public bool mol_p2 { get; set; }
        public Nullable<bool> mol_p2_1 { get; set; }
        public Nullable<bool> mol_p2_2 { get; set; }
        public string mol_p2_2_1 { get; set; }
        public Nullable<bool> mol_p2_3 { get; set; }
        public string mol_p2_3_1 { get; set; }
        public string mol_p3_1 { get; set; }
        public string mol_p4_1 { get; set; }
        public int mol_p4_2 { get; set; }
        public bool mol_p5 { get; set; }
        public bool mol_p6 { get; set; }
        public Nullable<bool> mol_p6_1 { get; set; }
        public Nullable<bool> mol_p6_2 { get; set; }
        public string mol_p7 { get; set; }
        public string mol_p8 { get; set; }
        public bool pro_p1 { get; set; }
        public string pro_p1_1 { get; set; }
        public string pro_p1_21 { get; set; }
        public Nullable<int> pro_p1_22 { get; set; }
        public string pro_p1_3 { get; set; }
        public string pro_p1_4 { get; set; }
        public bool pro_p2 { get; set; }
        public Nullable<int> pro_p2_1 { get; set; }
        public string pro_p2_11 { get; set; }
        public string pro_p2_21 { get; set; }
        public Nullable<int> pro_p2_22 { get; set; }
        public string pro_p2_3 { get; set; }
        public Nullable<bool> pro_p2_4_1 { get; set; }
        public Nullable<bool> pro_p2_4_2 { get; set; }
        public string pre_p1A { get; set; }
        public bool pre_p1Acheck { get; set; }
        public string pre_p1B { get; set; }
        public bool pre_p1Bcheck { get; set; }
        public string pre_p2 { get; set; }
        public string ind_p1 { get; set; }
        public Nullable<int> ind_p1_1 { get; set; }
        public string usu_reg { get; set; }
        public System.DateTime fec_reg { get; set; }
        public string usu_ult_upd { get; set; }
        public Nullable<System.DateTime> fec_ult_upd { get; set; }
        public Nullable<bool> mol_p6_3 { get; set; }
        public Nullable<bool> mol_p6_4 { get; set; }
        public string mol_p5_1 { get; set; }
    }
}
