//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_CLINICA_TEM_NEUROCEREBRO
    {
        public int numeroexamen { get; set; }
        public Nullable<bool> p1 { get; set; }
        public Nullable<int> p1_1 { get; set; }
        public string p1_2 { get; set; }
        public string p1_3 { get; set; }
        public Nullable<bool> p2 { get; set; }
        public string p2_1 { get; set; }
        public Nullable<bool> p3 { get; set; }
        public string p3_2 { get; set; }
        public Nullable<bool> p4 { get; set; }
        public string p4_1 { get; set; }
        public Nullable<int> p5 { get; set; }
        public Nullable<bool> p6 { get; set; }
        public string p6_1 { get; set; }
        public Nullable<int> p7 { get; set; }
        public string p8 { get; set; }
        public string p9 { get; set; }
        public string p10 { get; set; }
        public string p11 { get; set; }
        public string p12 { get; set; }
        public string p13 { get; set; }
        public string p14 { get; set; }
        public string p15 { get; set; }
        public string p16 { get; set; }
        public Nullable<int> p17 { get; set; }
        public string usu_reg { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public string usu_ult_upd { get; set; }
        public Nullable<System.DateTime> fec_ult_upd { get; set; }
        public Nullable<bool> p17_1 { get; set; }
        public Nullable<bool> p17_2 { get; set; }
        public Nullable<bool> p17_3 { get; set; }
        public Nullable<bool> p17_4 { get; set; }
        public Nullable<bool> p17_5 { get; set; }
        public Nullable<bool> p7_1 { get; set; }
        public Nullable<bool> p7_2 { get; set; }
        public Nullable<bool> p7_3 { get; set; }
        public Nullable<bool> p7_4 { get; set; }
        public Nullable<bool> p7_5 { get; set; }
    }
}
