//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_CLINICA_TEM_COLONOSCOPIA
    {
        public int numeroexamen { get; set; }
        public Nullable<bool> p1 { get; set; }
        public Nullable<int> p1_1 { get; set; }
        public string p1_2 { get; set; }
        public string p1_3 { get; set; }
        public Nullable<bool> p2 { get; set; }
        public string p2_1 { get; set; }
        public Nullable<bool> p3_1 { get; set; }
        public Nullable<bool> p3_2 { get; set; }
        public Nullable<bool> p3_3 { get; set; }
        public Nullable<bool> p3_4 { get; set; }
        public Nullable<bool> p3_5 { get; set; }
        public Nullable<bool> p3_6 { get; set; }
        public string p3_7 { get; set; }
        public Nullable<bool> p4 { get; set; }
        public Nullable<int> p4_1 { get; set; }
        public string p4_2 { get; set; }
        public string p4_3 { get; set; }
        public Nullable<bool> p5 { get; set; }
        public Nullable<int> p5_1 { get; set; }
        public string p5_2 { get; set; }
        public string p5_3 { get; set; }
        public string p6 { get; set; }
        public string p7 { get; set; }
        public Nullable<int> p8 { get; set; }
        public string usu_reg { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public string usu_ult_upd { get; set; }
        public Nullable<System.DateTime> fec_ult_upd { get; set; }
    }
}
