//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_CLINICA_TEM_CEREBRO
    {
        public int numeroexamen { get; set; }
        public bool p1 { get; set; }
        public string p1a { get; set; }
        public string p1a31 { get; set; }
        public bool p2 { get; set; }
        public Nullable<bool> p2a { get; set; }
        public bool p3 { get; set; }
        public Nullable<bool> p3a { get; set; }
        public Nullable<bool> p3a1 { get; set; }
        public Nullable<bool> p3a2 { get; set; }
        public string p3a3 { get; set; }
        public bool p4 { get; set; }
        public Nullable<bool> p4a { get; set; }
        public bool p5 { get; set; }
        public string p5a { get; set; }
        public string p5a41 { get; set; }
        public bool p6 { get; set; }
        public string p6a { get; set; }
        public string p6a71 { get; set; }
        public string p7 { get; set; }
        public string p8 { get; set; }
        public bool p9 { get; set; }
        public bool p10 { get; set; }
        public string p10a { get; set; }
        public string p10a71 { get; set; }
        public bool p11 { get; set; }
        public Nullable<int> p11a { get; set; }
        public string p11b { get; set; }
        public string p11c { get; set; }
        public bool p12 { get; set; }
        public Nullable<bool> p12aa { get; set; }
        public Nullable<bool> p12bb { get; set; }
        public string p12a { get; set; }
        public string p12a41 { get; set; }
        public string p12b { get; set; }
        public string p12c { get; set; }
        public string p12d { get; set; }
        public string p12d41 { get; set; }
        public string p12e { get; set; }
        public string p12f { get; set; }
        public string p13A { get; set; }
        public bool p13Acheck { get; set; }
        public string p13B { get; set; }
        public bool p13Bcheck { get; set; }
        public string p14 { get; set; }
        public Nullable<bool> p15_1 { get; set; }
        public Nullable<bool> p15_2 { get; set; }
        public Nullable<bool> p15_3 { get; set; }
        public Nullable<bool> p15_4 { get; set; }
        public Nullable<bool> p15_5 { get; set; }
        public string p16 { get; set; }
        public Nullable<int> p16_1 { get; set; }
        public string usu_reg { get; set; }
        public System.DateTime fec_reg { get; set; }
        public string usu_ult_upd { get; set; }
        public Nullable<System.DateTime> fec_ult_upd { get; set; }
        public string p9a1 { get; set; }
    }
}
