//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_CLINICA_MAMA
    {
        public int numeroexamen { get; set; }
        public bool p1 { get; set; }
        public Nullable<bool> p1_1 { get; set; }
        public Nullable<bool> p1_2 { get; set; }
        public Nullable<bool> p1_3 { get; set; }
        public Nullable<bool> p1_4 { get; set; }
        public Nullable<bool> p1_5 { get; set; }
        public Nullable<bool> p1_6 { get; set; }
        public Nullable<bool> p1_1_1 { get; set; }
        public Nullable<bool> p1_2_2 { get; set; }
        public Nullable<bool> p1_3_1 { get; set; }
        public Nullable<bool> p1_4_1 { get; set; }
        public Nullable<bool> p1_5_1 { get; set; }
        public Nullable<bool> p1_6_1 { get; set; }
        public Nullable<int> p2 { get; set; }
        public Nullable<int> p2_1 { get; set; }
        public Nullable<bool> p3 { get; set; }
        public string p3_1 { get; set; }
        public Nullable<bool> p4 { get; set; }
        public string p4_1 { get; set; }
        public string p4_2 { get; set; }
        public Nullable<int> p4_2_1 { get; set; }
        public Nullable<bool> p4_3 { get; set; }
        public string p4_4 { get; set; }
        public string p5 { get; set; }
        public string p6 { get; set; }
        public string p7 { get; set; }
        public string p8 { get; set; }
        public string ind_p1 { get; set; }
        public Nullable<int> ind_p1_1 { get; set; }
        public string usu_reg { get; set; }
        public System.DateTime fec_reg { get; set; }
        public string usu_ult_upd { get; set; }
        public Nullable<System.DateTime> fec_ult_upd { get; set; }
        public string p1_0 { get; set; }
        public Nullable<bool> p9 { get; set; }
        public string p9_1 { get; set; }
        public Nullable<int> p9_2 { get; set; }
        public bool p10 { get; set; }
    }
}
