//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_CLINICA_GENERICA_EMETAC
    {
        public int numeroexamen { get; set; }
        public Nullable<bool> p1 { get; set; }
        public string p1_1 { get; set; }
        public Nullable<int> p2_1 { get; set; }
        public Nullable<int> p2_2 { get; set; }
        public Nullable<bool> p3 { get; set; }
        public string p4 { get; set; }
        public Nullable<int> p5 { get; set; }
        public string p6 { get; set; }
        public string p7 { get; set; }
        public Nullable<bool> p8 { get; set; }
        public string usu_reg { get; set; }
        public Nullable<System.DateTime> fec_reg { get; set; }
        public string usu_ult_upd { get; set; }
        public Nullable<System.DateTime> fec_ult_upd { get; set; }
    }
}
