//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HONORARIOTECNOLOGO
    {
        public int codigohonorariotecnologo { get; set; }
        public int codigopaciente { get; set; }
        public int codigoequipo { get; set; }
        public string tecnologoturno { get; set; }
        public System.DateTime horaestudio { get; set; }
        public System.DateTime fechaestudio { get; set; }
        public string turno { get; set; }
        public int placamalogro { get; set; }
        public int placauso { get; set; }
        public int codequiporealizo { get; set; }
        public bool procesar { get; set; }
        public Nullable<bool> sedacion { get; set; }
        public Nullable<bool> contraste { get; set; }
        public Nullable<bool> tecnicas { get; set; }
        public Nullable<bool> contraste_continuo { get; set; }
        public string comentarios { get; set; }
        public bool isRevisado { get; set; }
        public Nullable<System.DateTime> fec_revisa { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
