//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMEMEDICO
    {
        public int numeroinforme { get; set; }
        public string codigoestudio { get; set; }
        public System.DateTime fechainforme { get; set; }
        public System.DateTime fecharevision { get; set; }
        public bool impreso { get; set; }
        public int codigoclase { get; set; }
        public int codigopaciente { get; set; }
        public string medicoinforma { get; set; }
        public byte[] cuerpoinforme { get; set; }
        public string medicorevisa { get; set; }
        public Nullable<bool> SinInforme { get; set; }
        public Nullable<System.DateTime> FirmaFecha { get; set; }
        public string FirmaUsuario { get; set; }
        public Nullable<int> CantImpreso { get; set; }
        public string TranscriUsu { get; set; }
        public Nullable<System.DateTime> TranscriFec { get; set; }
        public string CuerpoTranscri { get; set; }
        public string CuerpoRealiza { get; set; }
        public string CuerpoValida { get; set; }
        public string CuerpoFirma { get; set; }
        public Nullable<int> CuerpoRealizaIns { get; set; }
        public Nullable<int> CuerpoRealizaDel { get; set; }
        public Nullable<int> CuerpoValidaIns { get; set; }
        public Nullable<int> CuerpoValidaDel { get; set; }
        public Nullable<int> CuerpoFirmaIns { get; set; }
        public Nullable<int> CuerpoFirmaDel { get; set; }
        public Nullable<int> CuerpoValidaTotal { get; set; }
        public Nullable<int> CuerpoRealizaTotal { get; set; }
        public Nullable<int> CuerpoFirmaTotal { get; set; }
        public Nullable<int> CuerpoTranscriTotal { get; set; }
        public string ImpactoDeValidacion { get; set; }
        public Nullable<int> CuerpoValidaMov { get; set; }
        public string MedAsigValid { get; set; }
        public Nullable<decimal> PForma { get; set; }
        public string PFondo { get; set; }
        public Nullable<int> pcinforma { get; set; }
        public Nullable<int> pcrevisa { get; set; }
        public Nullable<int> pcfirma { get; set; }
        public string MedAsigMotivo { get; set; }
    
        public virtual ESTUDIO ESTUDIO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
