//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insti_Prom_Medico
    {
        public int id_asig { get; set; }
        public string cod_clinica { get; set; }
        public string nom_clinica { get; set; }
        public string cod_promotor { get; set; }
        public string nom_promotor { get; set; }
        public string cmp_medico { get; set; }
        public string nom_medico { get; set; }
        public System.DateTime fec_asig { get; set; }
        public string usu_asig { get; set; }
        public bool estado { get; set; }
    }
}
