//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumo_Cum_Sunasa
    {
        public Insumo_Cum_Sunasa()
        {
            this.Detalle_Contraste = new HashSet<Detalle_Contraste>();
            this.Detalle_Sedacion = new HashSet<Detalle_Sedacion>();
        }
    
        public int idInsumo { get; set; }
        public string codigoCUM { get; set; }
        public string producto { get; set; }
        public string forma_farmaceutica { get; set; }
        public string forma_presentacion { get; set; }
        public string propietario_registro { get; set; }
        public string fabricante { get; set; }
        public string unidad_reporte { get; set; }
        public string principo_activo { get; set; }
        public Nullable<int> medida { get; set; }
        public string unidad_medida { get; set; }
        public string Unidad_posologica { get; set; }
        public string atc { get; set; }
        public string descripcion_atc { get; set; }
        public bool isactivo { get; set; }
        public bool isRM { get; set; }
        public bool isTEM { get; set; }
        public bool isSedacion { get; set; }
    
        public virtual ICollection<Detalle_Contraste> Detalle_Contraste { get; set; }
        public virtual ICollection<Detalle_Sedacion> Detalle_Sedacion { get; set; }
    }
}
