//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MED_PRE_ENTREVISTA
    {
        public int numeroatencion { get; set; }
        public bool CheckBox1 { get; set; }
        public bool CheckBox2 { get; set; }
        public bool CheckBox3 { get; set; }
        public bool CheckBox4 { get; set; }
        public bool CheckBox5 { get; set; }
        public bool CheckBox6 { get; set; }
        public bool CheckBox7 { get; set; }
        public bool CheckBox8 { get; set; }
        public bool CheckBox9 { get; set; }
        public bool CheckBox10 { get; set; }
        public bool CheckBox11 { get; set; }
        public bool CheckBox12 { get; set; }
        public bool CheckBox13 { get; set; }
        public bool CheckBox14 { get; set; }
        public bool CheckBox15 { get; set; }
        public bool CheckBox16 { get; set; }
        public bool CheckBox17 { get; set; }
        public bool CheckBox18 { get; set; }
        public bool CheckBox19 { get; set; }
        public bool CheckBox20 { get; set; }
        public bool CheckBox21 { get; set; }
        public string txtOtros { get; set; }
        public bool CheckBox30 { get; set; }
        public bool CheckBox31 { get; set; }
        public string txtNumeroConsentimiento { get; set; }
        public bool isAutorizado { get; set; }
        public Nullable<int> tipoAutorizacion { get; set; }
        public string detalleAutorizacion { get; set; }
        public string usu_reg { get; set; }
        public System.DateTime fec_reg_ini { get; set; }
        public System.DateTime fec_reg_fin { get; set; }
        public Nullable<int> modalidad { get; set; }
    }
}
