//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motivo_Entre_Turno
    {
        public Motivo_Entre_Turno()
        {
            this.Solicitud_Entre_Turno = new HashSet<Solicitud_Entre_Turno>();
        }
    
        public int idMotivo { get; set; }
        public string descripcion { get; set; }
        public bool isActivo { get; set; }
        public int tipo { get; set; }
    
        public virtual ICollection<Solicitud_Entre_Turno> Solicitud_Entre_Turno { get; set; }
    }
}
