//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int id { get; set; }
        public int idAplicativo { get; set; }
        public System.DateTime fec_register { get; set; }
        public string usuario { get; set; }
        public bool isArea { get; set; }
        public bool isRevisado { get; set; }
        public string referencia { get; set; }
    
        public virtual Aplicativo Aplicativo { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
