//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTPROCESO
    {
        public int codigopostproceso { get; set; }
        public int numeroestudio { get; set; }
        public int codigopaciente { get; set; }
        public string codigoestudio { get; set; }
        public string codigousuario { get; set; }
        public string descripcion { get; set; }
        public int cantidadplaca { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> placamalogro { get; set; }
        public Nullable<int> placaprueba { get; set; }
        public Nullable<int> placareimpresa { get; set; }
        public Nullable<int> codigoequipo { get; set; }
        public string estado { get; set; }
        public string tipo { get; set; }
        public string motivocancelacion { get; set; }
    }
}
