//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRODETECNICA
    {
        public int correlativo { get; set; }
        public int numeroestudio { get; set; }
        public string codigoestudio { get; set; }
        public string codigotecnica { get; set; }
        public string nombretecnica { get; set; }
        public int codigoequipo { get; set; }
        public int codigoclase { get; set; }
    }
}
