//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sedacion
    {
        public Sedacion()
        {
            this.Detalle_Sedacion = new HashSet<Detalle_Sedacion>();
        }
    
        public int idsedacion { get; set; }
        public int numeroexamen { get; set; }
        public int paciente { get; set; }
        public string usuario { get; set; }
        public string tecnologo { get; set; }
        public string consentimiento { get; set; }
        public string tipo_sedacion { get; set; }
        public string motivo_sedacion { get; set; }
        public string motivo_otros { get; set; }
        public Nullable<bool> f1 { get; set; }
        public string f1_1 { get; set; }
        public string f1_2 { get; set; }
        public Nullable<bool> f2 { get; set; }
        public string f2_1 { get; set; }
        public string f2_2 { get; set; }
        public Nullable<bool> f3 { get; set; }
        public string f3_1 { get; set; }
        public string f3_2 { get; set; }
        public Nullable<bool> f4 { get; set; }
        public string f4_1 { get; set; }
        public string f4_2 { get; set; }
        public Nullable<bool> f5 { get; set; }
        public string f5_1 { get; set; }
        public string f5_2 { get; set; }
        public Nullable<bool> f6 { get; set; }
        public string f6_1 { get; set; }
        public string f6_2 { get; set; }
        public Nullable<bool> f7 { get; set; }
        public string f7_1 { get; set; }
        public string f7_2 { get; set; }
        public Nullable<bool> i1 { get; set; }
        public string i1_1 { get; set; }
        public string i1_2 { get; set; }
        public Nullable<bool> i2 { get; set; }
        public string i2_1 { get; set; }
        public Nullable<bool> i3 { get; set; }
        public Nullable<int> i3_1 { get; set; }
        public string i3_2 { get; set; }
        public Nullable<bool> i4 { get; set; }
        public Nullable<int> i4_1 { get; set; }
        public string i4_2 { get; set; }
        public Nullable<bool> i5 { get; set; }
        public Nullable<int> i5_1 { get; set; }
        public string i5_2 { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_impresion { get; set; }
        public Nullable<System.DateTime> fecha_tecnologo { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> atencion { get; set; }
    
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual USUARIO USUARIO2 { get; set; }
        public virtual ICollection<Detalle_Sedacion> Detalle_Sedacion { get; set; }
    }
}
