//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegUsuarioXRol
    {
        public int SegRolId { get; set; }
        public string codigousuario { get; set; }
        public System.DateTime FecReg { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
