//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSAL
    {
        public SUCURSAL()
        {
            this.SUCURSALXUSUARIO = new HashSet<SUCURSALXUSUARIO>();
        }
    
        public int codigosucursal { get; set; }
        public int codigounidad { get; set; }
        public string descripcion { get; set; }
        public string ShortDesc { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string contenido { get; set; }
        public string direccion { get; set; }
        public Nullable<bool> isVisible { get; set; }
        public string horario { get; set; }
        public string angulo { get; set; }
        public string sede { get; set; }
        public string nombreweb { get; set; }
        public string urlGoogleMaps { get; set; }
        public string imageName { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string direccionfactura { get; set; }
    
        public virtual UNIDADNEGOCIO UNIDADNEGOCIO { get; set; }
        public virtual ICollection<SUCURSALXUSUARIO> SUCURSALXUSUARIO { get; set; }
    }
}
