//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKT_Ticketera
    {
        public int id_Ticket { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_tipo_aten { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> idSede { get; set; }
        public Nullable<System.DateTime> fec_registro { get; set; }
        public Nullable<System.DateTime> fec_llamada { get; set; }
        public string usu_llamada { get; set; }
        public Nullable<System.DateTime> fec_termino { get; set; }
        public string usu_termino { get; set; }
        public Nullable<System.DateTime> fec_cancela { get; set; }
        public string usu_cancela { get; set; }
        public Nullable<int> id_counter { get; set; }
        public string motivo_cancela { get; set; }
        public bool isEliminado { get; set; }
        public bool isPreferencial { get; set; }
        public bool isImpreso { get; set; }
        public bool isrecojo { get; set; }
        public bool isEmergencia { get; set; }
        public Nullable<System.DateTime> fec_caja { get; set; }
        public string usu_caja { get; set; }
        public int idempresa { get; set; }
        public bool isRellamada { get; set; }
    }
}
