//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CARTAGARANTIA = new HashSet<CARTAGARANTIA>();
            this.CARTAGARANTIA1 = new HashSet<CARTAGARANTIA>();
            this.CARTAGARANTIA2 = new HashSet<CARTAGARANTIA>();
            this.Contraste = new HashSet<Contraste>();
            this.Contraste1 = new HashSet<Contraste>();
            this.Encuesta_Satisfaccion = new HashSet<Encuesta_Satisfaccion>();
            this.INFORMEMEDICO = new HashSet<INFORMEMEDICO>();
            this.Notificaciones = new HashSet<Notificaciones>();
            this.SegUsuarioXRol = new HashSet<SegUsuarioXRol>();
            this.Sedacion = new HashSet<Sedacion>();
            this.Sedacion1 = new HashSet<Sedacion>();
            this.SUCURSALXUSUARIO = new HashSet<SUCURSALXUSUARIO>();
            this.SupervisarEncuesta = new HashSet<SupervisarEncuesta>();
            this.SupervisarEncuesta1 = new HashSet<SupervisarEncuesta>();
            this.SupervisarEncuesta2 = new HashSet<SupervisarEncuesta>();
        }
    
        public int jerarquia { get; set; }
        public string estadousuario { get; set; }
        public string siglas { get; set; }
        public string codigousuario { get; set; }
        public string dni { get; set; }
        public bool bloqueado { get; set; }
        public string contrasena { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> isEnf { get; set; }
        public Nullable<bool> isAnes { get; set; }
        public string username { get; set; }
        public string Acro { get; set; }
        public Nullable<int> CurrentUnidad { get; set; }
        public bool isSessionLocked { get; set; }
        public string User_Uid { get; set; }
        public Nullable<int> AreaId { get; set; }
    
        public virtual ICollection<CARTAGARANTIA> CARTAGARANTIA { get; set; }
        public virtual ICollection<CARTAGARANTIA> CARTAGARANTIA1 { get; set; }
        public virtual ICollection<CARTAGARANTIA> CARTAGARANTIA2 { get; set; }
        public virtual ICollection<Contraste> Contraste { get; set; }
        public virtual ICollection<Contraste> Contraste1 { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<Encuesta_Satisfaccion> Encuesta_Satisfaccion { get; set; }
        public virtual ICollection<INFORMEMEDICO> INFORMEMEDICO { get; set; }
        public virtual ICollection<Notificaciones> Notificaciones { get; set; }
        public virtual ICollection<SegUsuarioXRol> SegUsuarioXRol { get; set; }
        public virtual ICollection<Sedacion> Sedacion { get; set; }
        public virtual ICollection<Sedacion> Sedacion1 { get; set; }
        public virtual ICollection<SUCURSALXUSUARIO> SUCURSALXUSUARIO { get; set; }
        public virtual ICollection<SupervisarEncuesta> SupervisarEncuesta { get; set; }
        public virtual ICollection<SupervisarEncuesta> SupervisarEncuesta1 { get; set; }
        public virtual ICollection<SupervisarEncuesta> SupervisarEncuesta2 { get; set; }
    }
}
